"""Turn measured figure data into traceable, chapter-specific discussion blocks."""
from pathlib import Path

# Mechanism, engineering implication, and recommendation. These describe the
# model used in the chapter; numerical observations are supplied from each run.
CONTEXT = {
1: ("The equation of state links molecular interactions to density, compressibility and phase stability.", "A change in operating pressure alters both volumetric equipment load and the available production margin.", "Carry the actual fluid composition and operating envelope into the downstream capacity study."),
2: ("SRK and Peng–Robinson resolve non-ideal gas behavior differently; transport properties require explicit property initialization after the flash.", "Property-model selection propagates into heat duty, hydraulic loss and rotating-equipment demand.", "Compare model predictions with representative measurements before fixing design margins."),
3: ("Heavy-end characterization and equilibrium phase splitting control liquid dropout and the composition of the residual gas and liquid.", "A phase ratio is meaningful only where both phases exist; one-phase states must not be assigned an artificial ratio.", "Preserve the compositional basis and validate heavy-end properties against a measured PVT experiment."),
4: ("Pressure depletion changes fluid phase behavior, while the stated IPR and Corey equations describe assumed inflow and relative-permeability responses.", "Reservoir deliverability and fluid phase state impose different restrictions on the production system.", "Calibrate the inflow and saturation functions to well-test and core data; retain the reported two-phase domain for phase ratios."),
5: ("Upward hydrostatic head and rate-dependent friction oppose reservoir drawdown; the coupled operating point satisfies both the IPR and the wellhead-pressure boundary.", "A numerically attempted rate can exceed the pressure available from the reservoir and is then infeasible.", "Use the bracketed NeqSim operating-point solution and explicitly exclude failed pressure trials from design capacity."),
6: ("With imposed mass flow, reducing the effective choke opening increases resistance; the pressure-calculation mode must be selected explicitly.", "Some openings cannot pass the imposed rate while maintaining positive downstream pressure.", "Select an opening within the feasible pressure envelope and re-solve reservoir deliverability before treating the fixed-rate sensitivity as a production forecast."),
7: ("Multiphase friction, elevation and thermal assumptions determine the subsea pressure–temperature path; the regime map is a conceptual aid.", "The same route can be limited by arrival pressure or by flow-assurance margin.", "Use the stated bathymetry and thermal boundary conditions, and investigate shutdown conditions separately from normal operation."),
8: ("Pipe diameter and actual phase velocities determine friction and liquid holdup through the Beggs–Brill calculation.", "A throughput claim is valid only where the pressure solution remains physical and the stated arrival-pressure allowance is met.", "Retain infeasible points in the numerical audit and bracket the capacity boundary rather than extrapolating through failures."),
9: ("Hydrate equilibrium depends on guest-gas fugacity and aqueous water activity; MEG lowers water activity and depresses the equilibrium temperature.", "Equilibrium margin is composition-specific and does not by itself predict hydrate formation kinetics or the success of a restart.", "Use the calculated inhibitor curve with an explicit temperature margin; treat the overlaid pipeline and shutdown paths as stated illustrative assumptions."),
10: ("Reducing pressure releases dissolved gas while redistributing hydrocarbons between vapor and liquid; Souders–Brown capacity also depends on the phase-density contrast.", "The pressure that improves oil recovery need not maximize separator gas-handling capacity.", "Evaluate the full staged separation train and verify vessel capacity at the candidate recovery optimum."),
11: ("Temperature and staged flashing redistribute light components between export oil and gas.", "Oil recovery, volatility and gas-compression duty can move in different directions as separator conditions change.", "Check the final export-quality specification on the actual stabilized liquid rather than using a single flash as a substitute for the train."),
12: ("Water equilibrium and expansion enthalpy determine the achievable gas dryness, temperature and liquid recovery.", "Cooling and dehydration targets must be checked together because a pressure or temperature change can create an additional liquid phase.", "Reflash the export stream at the contractual reference conditions and verify the hydrate margin at the selected operating point."),
13: ("The three-phase flash allocates water, hydrocarbon liquid and gas according to the input composition and operating conditions.", "Water mole fraction in a fluid recipe is different from standard-liquid water cut and from treatment-system hydraulic load.", "State the composition basis explicitly and size water handling from the calculated water outlet flow, followed by a separate contaminant-removal model."),
14: ("Compression raises gas enthalpy; staging and intercooling change both the required shaft work and the discharge temperature.", "The minimum-power arrangement must also satisfy discharge-temperature and equipment-capacity limits.", "Compare stages on a common flow and pressure basis and preserve cooling duties in the utility balance."),
15: ("Compressor head, efficiency and operating limits depend on speed and volumetric flow; chart assumptions remain distinct from thermodynamic design-point calculations.", "A feasible power balance alone does not establish surge margin or stonewall margin.", "Replace illustrative curves with vendor-verified maps before using the operating envelope for control settings."),
16: ("Heat capacity, temperature approach and exchanger conductance jointly determine heat duty and outlet conditions.", "Increasing area has diminishing value when the limiting temperature approach is approached.", "Check thermal feasibility and pressure loss together, and reserve allowance for fouling and off-design operation."),
17: ("Throttling conserves enthalpy while the valve characteristic relates pressure loss to flow and opening.", "The specified-flow and specified-pressure calculation modes answer different questions and must not be mixed implicitly.", "Select the valve calculation mode explicitly and verify outlet pressure, phase state and any choking constraint."),
18: ("The screening fuel balance combines energy demand with the stated efficiency and ambient-derating assumptions.", "Calculated fuel demand and emissions depend on the assumed efficiency, load profile and fuel composition.", "Replace generic derating assumptions with the installed driver performance data before setting a site emissions or power commitment."),
19: ("Long-line friction and thermal behavior couple the export pressure requirement to diameter and throughput.", "A diameter choice affects both hydraulic margin and compression energy over the operating envelope.", "Validate roughness, route length and boundary pressures, then test the selected line over the full export-rate range."),
20: ("Capacity utilization is the current duty divided by an explicitly established equipment capacity.", "Auto-sizing establishes a screening reference; it does not verify an installed vessel or compressor nameplate.", "Replace inferred capacities with verified equipment limits before using the bottleneck result to authorize a rate increase."),
21: ("Relieving one active capacity constraint transfers the bottleneck to the next limiting unit.", "A local equipment upgrade can yield less system throughput than its standalone rating suggests.", "Re-run the complete train after each proposed upgrade and compare the incremental throughput with the required modification."),
22: ("The objective surface combines process outputs with the declared economic weights and constraints.", "An apparent optimum is conditional on the sampling domain and the treatment of infeasible points.", "Check nearby points and active constraints, then vary the economic assumptions separately from the physical model."),
23: ("The current FlowRateOptimizer evaluates the whole process and bisects throughput under the explicitly declared total-power limit.", "This screening result qualifies a power limit; unsupplied vessel ratings and vendor compressor maps remain outside its constraint set.", "Add verified equipment limits before promoting the screening rate to an operating recommendation, and re-run the selected point independently."),
24: ("Feasibility search tightens a bracket around the rate at which a declared equipment constraint becomes active.", "Agreement between search methods is meaningful only when they share the same process, objective and constraint definitions.", "Verify the final feasible and infeasible bracket endpoints with the complete process model."),
25: ("Utilization changes as process duties respond to flow and fluid state, causing the governing constraint to migrate through the train.", "Monitoring a single compressor can miss a separator, cooler or downstream bottleneck.", "Maintain a common time and model basis for all duty and capacity values, and show the active limiting unit with each rate recommendation."),
26: ("Each NeqSim WellFlow uses a pressure-squared inflow relationship calibrated to its declared design rate; manifold pressure and added choke loss reduce available drawdown.", "This is an inflow-only gathering illustration; tubing hydraulics and dynamic reservoir depletion are not included.", "Calibrate each inflow coefficient to well tests, then add tubing and shared-header losses before scheduling real well rates."),
27: ("Fluid composition changes phase split and compression demand, shifting the rate that fits the same assumed equipment limits.", "An operating point feasible for the base composition may be infeasible for a richer or wetter scenario.", "Retain the limiting plausible scenario or assign justified scenario probabilities before selecting a robust production target."),
28: ("The production VFP calculation inverts an upward-flow NeqSim pipeline for the inlet pressure required to meet each specified wellhead-pressure boundary.", "Running a forward downward-flow model would reverse the friction contribution and would describe injection rather than production.", "Use the reported boundary residuals to check every VFP point and preserve the inlet-temperature, roughness and fluid assumptions with the exported table."),
29: ("The illustrative Python inventory balance increases outlet-valve opening when level exceeds its setpoint; the gain comparison changes the closed-loop response.", "These trajectories explain controller action and tuning but are not a validation of NeqSim transient vessel behavior.", "Use a separately validated dynamic vessel model with inventory and energy closure before applying the illustrative gains to a real control loop."),
30: ("ProcessAutomation reads the computed model state through explicit variable addresses; synthetic sensor noise is added only for the comparison exercise.", "A synthetic residual can demonstrate monitoring logic but cannot establish agreement with an operating plant.", "Map actual historian tags, units, timestamps and measurement uncertainty before interpreting a residual as model drift."),
31: ("The recycle residuals are measured from repeated NeqSim equipment evaluations, while flash timings reflect the current machine and runtime state.", "A small solver residual supports internal convergence; it is distinct from accuracy against independent experimental data.", "Check physical balances and the actual adjusted target after convergence, and repeat timing studies under controlled conditions before drawing performance conclusions."),
32: ("Every Pareto candidate runs the NeqSim compressor at a stated efficiency and throughput; non-dominated candidates maximize production while minimizing total shaft power.", "The frontier expresses a physical production–energy trade-off conditional on the assumed achievable efficiencies.", "Use verified efficiency maps and business constraints to select a point from the frontier; do not infer an economic optimum from Pareto membership alone."),
33: ("The CPA SimpleTEGAbsorber re-evaluates phase equilibrium and staged contacting at every solvent circulation rate, with explicit lean-solvent purity and stage efficiency.", "The dehydration result depends on solvent condition as well as circulation, and an illustrative water target is not a universal gas contract.", "Confirm lean-TEG purity and contacting efficiency and evaluate regeneration duty before increasing solvent circulation."),
34: ("Sequential separation and compression couple recovered product rates to the work and cooling duties of the integrated plant.", "Equipment changes must be assessed against the complete material and energy paths, not only the local unit.", "Reconcile all export and utility streams and review the limiting equipment under the same fluid and throughput assumptions."),
35: ("SRK predicts the CO2-rich mixture properties, while ISO 6976 computes the hydrogen-blend calorific properties from consistent composition and reference-state definitions.", "Pure-CO2 critical properties are not a mixture transport envelope, and Wobbe index alone does not establish appliance interchangeability.", "Use a validated mixture phase model for CO2 transport and a complete gas-quality specification for hydrogen blending."),
}


def describe(record, chapter_number, chapter_path, notebook_name):
    candidates = [s for s in record["series"] if s["y_min"] is not None and s["n_points"] >= 3]
    candidates.sort(key=lambda s: (s["y_max"] != s["y_min"], s["n_points"]), reverse=True)
    chosen = candidates[0] if candidates else None
    title = next((s["title"] for s in record["series"] if s["title"]), Path(record["path"]).stem.replace("_", " "))
    title = " ".join(title.split())
    if chosen:
        quantity = chosen["y_label"] or "plotted ordinate"
        observation = "The executed series '{}' spans {:.5g} to {:.5g} in {} across {} finite plotted points.".format(
            chosen["series"], chosen["y_min"], chosen["y_max"], quantity,
            chosen["n_points"] - chosen["n_nonfinite"])
    else:
        observation = "The figure presents the stated chapter comparison or schematic; use the accompanying notebook for its explicit assumptions and numerical inputs."
    missing = sum(s["n_nonfinite"] for s in record["series"])
    if missing:
        observation += " {} plotted entries are undefined or infeasible and remain omitted from the continuous curves; the notebook records the relevant domain or failure.".format(missing)
    mechanism, implication, recommendation = CONTEXT[chapter_number]
    caption = title + ". " + observation
    rows = [[s["series"], s["y_label"], s["y_min"], s["y_max"], s["n_points"]-s["n_nonfinite"], s["n_nonfinite"]]
            for s in candidates[:5]]
    return {"chapter": chapter_path, "chapter_number": chapter_number,
            "figure": Path(record["path"]).name, "figure_path": "figures/" + Path(record["path"]).name,
            "caption": caption, "title": title, "observation": observation,
            "mechanism": mechanism, "implication": implication, "recommendation": recommendation,
            "notebook": "notebooks/" + notebook_name, "dpi": record["dpi"], "sha256": record["sha256"],
            "table": {"headers": ["Series", "Output / unit", "Minimum", "Maximum", "Finite points", "Undefined points"], "rows": rows}}


def markdown(item):
    return "**Executed-figure discussion.** " + item["observation"] + "\n\n**Physical mechanism.** " + item["mechanism"] + "\n\n**Engineering implication.** " + item["implication"] + "\n\n**Recommendation.** " + item["recommendation"] + "\n"
