"""Final source editorial pass: preserve code; authorized legacy placements only."""
from pathlib import Path
import re,json,hashlib,datetime
B=Path(__file__).resolve().parents[1];V=B/'verification/scientific_revision';backup=B/'.build/final_editorial_foundations';backup.mkdir(exist_ok=True,parents=True)
paths=sorted((B/'chapters').glob('ch*/chapter.md'))[:18];before={p.parent.name:p.read_text(encoding='utf-8') for p in paths};fixes=[];removed=[]
fences=re.compile(r'^```[^\n]*\n.*?^```[^\n]*(?:\n|$)',re.M|re.S)
images=re.compile(r'^!\[([^\n]*)\]\(([^\n]*)\)',re.M)
inv=json.loads((V/'manuscript_figures/inventory.json').read_text(encoding='utf-8'));review=json.loads((V/'manuscript_figure_review.json').read_text(encoding='utf-8'))
for ch,name,reason in [('ch05','pressure_traverse.png','Manufactured pressure traces were presented as flow-dependent well solutions; the literal calculation reports rate-dependent wellhead endpoint values.'),('ch08','pipeline_pt_profiles.png','Manufactured profiles conflict with the caption distance and do not match the executed hydraulic case; retain actual terminal-pressure/temperature results.')]:
 p=next(p for p in paths if p.parent.name.startswith(ch));t=p.read_text(encoding='utf-8');asset=p.parent/'figures'/name;digest=hashlib.sha256(asset.read_bytes()).hexdigest();original=next(x for x in inv if x['chapter']==p.parent.name and Path(x['path']).name==name)
 assert digest==original['sha256'],str(asset)+' changed since original inventory'
 match=next(m for m in images.finditer(t) if Path(m[2]).name==name)
 (backup/(p.parent.name+'.md')).write_text(t,encoding='utf-8');t=t[:match.start()]+t[match.end():];p.write_text(t,encoding='utf-8')
 r={'chapter':p.parent.name,'file':name,'action':'removed_unsupported_legacy_placement','reason':reason,'old_sha256':digest}
 assert not any(x.get('chapter')==r['chapter'] and x.get('file')==name and x.get('action')==r['action'] for x in review['changes'])
 review['changes'].append(r);removed.append(r)
(V/'manuscript_figure_review.json').write_text(json.dumps(review,indent=2),encoding='utf-8')
# Correct future integration aliases without re-running global integration.
f=B/'devtools/integrate_scientific_illustrations.py';s=f.read_text(encoding='utf-8');s=s.replace("(5,'pressure_traverse_curves.png')","(5,'pressure_traverse.png')").replace("(8,'pipeline_profiles.png')","(8,'pipeline_pt_profiles.png')");f.write_text(s,encoding='utf-8')
def replace(ch,old,new,reason):
 p=next(p for p in paths if p.parent.name.startswith(ch));t=p.read_text(encoding='utf-8');assert old and t.count(old)==1,(ch,old[:100],t.count(old));
 if not (backup/(p.parent.name+'.md')).exists():(backup/(p.parent.name+'.md')).write_text(t,encoding='utf-8')
 p.write_text(t.replace(old,new),encoding='utf-8');fixes.append({'chapter':p.parent.name,'original':old,'correction':new,'reason':reason})
replace('ch03','- **Dry gas:** The phase envelope is so narrow that even surface conditions remain outside the two-phase region.','- **Dry gas:** The stated reservoir-to-surface path remains outside the hydrocarbon two-phase region. This classification depends on the composition and operating path; envelope width alone does not determine it.','Remove a width-based interpretation that relied on the retired hand-drawn classification envelopes.')
replace('ch05','To generate a pressure traverse (pressure vs. depth profile), the well can be run at multiple conditions or the internal profile can be examined:','The following fixed-bottomhole-pressure sweep reports the wellhead pressure and total pressure drop at each imposed rate. These are endpoint results, not depth profiles. The internal increment data can be examined separately to construct pressure traverses; rates for which the hydraulic calculation fails remain rejected.','The removed plot claimed depth profiles, whereas the literal example prints only endpoint values.')
replace('ch07','A tieback feasibility study systematically evaluates production rate and arrival conditions over a range of flowline lengths:','The following tieback screen calculates arrival pressure and temperature across a range of flowline lengths at one fixed feed rate. A feasible tieback also requires a stated receiving-pressure requirement and separate flow-assurance and shutdown criteria; this table alone does not establish a maximum feasible distance.','The removed synthetic distance plot implied unsupported tieback feasibility and a fixed hydrate threshold.')
replace('ch08','To extract the full pressure and temperature profile along the pipeline, NeqSim divides the pipeline into increments (set by `setNumberOfIncrements`). Each increment performs a local flash calculation and pressure/temperature step:','NeqSim divides the pipeline into increments (set by `setNumberOfIncrements`) and updates pressure, temperature and local phase properties along the route. The following diameter comparison reports only each line\'s outlet pressure and temperature. These endpoint results must not be read as a plotted profile; the stored increment data can be inspected separately.','The removed synthetic profile did not represent the literal endpoint comparison.')
replace('ch09','The hydrate curve can be superimposed on the pipeline operating conditions to assess risk:','The following calculation tabulates hydrate-equilibrium temperature against pressure for the stated composition. Compare these values with a separately calculated operating path and its uncertainty; this example does not plot an inhibited boundary or establish blockage probability.','Clarify the actual tabular result after removing the incorrect inhibitor-curve placement.')
replace('ch09','The degree of subcooling below the hydrate equilibrium temperature determines the severity of the hydrate risk:','Subcooling measures the temperature driving force relative to the calculated hydrate-equilibrium boundary. Blockage risk also depends on free-water availability, kinetics, residence time, flow history and inhibition; subcooling alone does not determine its severity:','Avoid retaining the universal safe-window interpretation of the removed plot.')
replace('ch09','| $< 0$ °C | No risk | Normal operation (outside hydrate zone) |','| $< 0$ °C | Outside the calculated hydrate-stability region | Check uncertainty and possible cooling or pressure transients |','An equilibrium state outside the region is not a universal no-risk certificate.')
replace('ch09','| Subcooling $\\Delta T_{sub}$ | Risk Level | Typical Response |','The following bins are illustrative screening categories, not validated blockage-risk levels or universal intervention requirements. Select mitigation using the fluid, water and operating-history evidence for the case.\n\n| Subcooling $\\Delta T_{sub}$ | Illustrative category | Example mitigation to assess |','Scope remaining adjacent subcooling table after removal of unsupported safe-window graphic.')
replace('ch09','A comprehensive flow assurance screening overlays all threat boundaries on the same P-T diagram:','This screening example calculates a hydrate curve and lists assumed pipeline states for comparison. The raw saturation trace, hydrate calculation and assumed operating points retain separate acceptance limits; they do not define a comprehensive safe operating window.','The original introductory claim depended on the retired synthetic comprehensive-envelope figure.')
replace('ch16','![Figure 16.5: Duty vs. UA](figures/ch14_ua_sizing.png)','![Figure 16.5: Recovered heat duty and thermal effectiveness versus overall conductance UA for the specified two-stream heat exchanger](figures/ch14_ua_sizing.png)','Make the caption describe both panels and the actual declared conductance sensitivity without changing numbering or placement.')
# Validate invariants and inspect every explicit figure reference outside code/images.
chapters=[];refs=[];errors=[]
for p in paths:
 name=p.parent.name;t=p.read_text(encoding='utf-8');orig=before[name];assert fences.findall(t)==fences.findall(orig),'Code fence changed '+name
 prior=[(m[1],m[2]) for m in images.finditer(orig)];after=[(m[1],m[2]) for m in images.finditer(t)]
 removednames={x['file'] for x in removed if x['chapter']==name};expected=[(c,u) for c,u in prior if Path(u).name not in removednames]
 assert [u for c,u in expected]==[u for c,u in after],'Unexpected placement/reordering '+name
 assert [re.match(r'Figure (\d+\.\d+)',c)[1] for c,u in expected]==[re.match(r'Figure (\d+\.\d+)',c)[1] for c,u in after],'Figure number changed '+name
 labels={re.match(r'Figure (\d+\.\d+)',c)[1]:u for c,u in after}
 clean=fences.sub(lambda m:'\n'*m[0].count('\n'),t);clean=images.sub('',clean)
 for m in re.finditer(r'\b(?:Figure|Fig\.)\s+(\d+\.\d+)\b',clean,re.I):
  label=m[1];row={'chapter':name,'label':label,'line':clean[:m.start()].count('\n')+1,'target':labels.get(label),'status':'pass' if label in labels else 'unresolved'};refs.append(row)
  if label not in labels:errors.append(row)
 dangling=[line for line in clean.splitlines() if re.search(r'(?i)\b(?:figure below|figure above|following figure|preceding figure|diagram below|plot below|plot above)\b',line)]
 if dangling:errors.append({'chapter':name,'deictic_references':dangling})
 chapters.append({'chapter':name,'source_sha256':hashlib.sha256(t.encode()).hexdigest(),'before_sha256':hashlib.sha256(orig.encode()).hexdigest(),'code_unchanged':True,'code_fence_count':len(fences.findall(t)),'figure_count':len(after),'image_order_and_numbers_preserved_except_authorized_removals':True,'figure_references_inspected':True,'fix_count':sum(x['chapter']==name for x in fixes)})
report={'status':'pass' if not errors else 'fail','inspected_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'scope':'Adjacent manuscript prose at removed legacy figure placements in chapters03/05/07/08/09; explicit figure cross-references and orphan-caption/deictic-reference search across chapters01–18; parent-requested16.5caption improvement. This pass does not rerun code or revalidate unchanged calculations.','chapters':chapters,'adjacent_sections_inspected':['3.2.2','3.4.4','3.7.4 Separator Test Simulation','5.4.2','7.6.2–7.6.3','8.3.3–8.3.4','8.5.2','9.2.5–9.2.6','9.10.1','16 reproduced UA-results discussion'],'fixes':fixes,'authorized_removals':removed,'figure_references':refs,'unresolved':errors,'next_root_action':'Normalize figure numbering after the two authorized removals; deliberate number gaps remain in chapters05/08. No code or calculation changes.'}
(V/'final_editorial_foundations.json').write_text(json.dumps(report,indent=2,ensure_ascii=False),encoding='utf-8');print(report['status'],len(chapters),'chapters',len(fixes),'prose/caption fixes',len(removed),'verified removals',len(refs),'explicit prose figure references')
if errors:print(errors);raise SystemExit(1)
