"""Add case-specific verification scope without promoting numerical checks to calibration."""
from pathlib import Path
import re,json
B=Path(__file__).resolve().parents[1]
notes={
'ch01':('The pressure budget now separates reservoir drawdown from downstream losses, and the water-column pressure estimate is checked by an independent unit conversion. The separator flowsheet has finite-state, component, mass and enthalpy checks; these checks support its calculated phase allocation, while export limits in the chapter remain illustrative contract inputs.','foundationSLBgradient'),
'ch02':('The worked TP flashes are checked for phase-fraction normalization, reconstruction of feed composition and equality of phase fugacities. Hydrate calculations are checked for finite temperatures only; neither a converged flash nor a physically plausible hydrate temperature establishes empirical accuracy. Independent methane reference-EOS comparisons are reported separately, with their own state range and teaching tolerance.','michelsen1982,kunz2012'),
'ch03':('The characterized-fluid examples retain explicit heavy-end assumptions and distinguish mole normalization from mass conservation. The bubble-pressure regression has a numerical residual test, but it fits a synthetic target and is not laboratory validation. The TBP phase-envelope trace in Section 3.7.5 is explicitly rejected as a complete envelope; finite getter arrays alone do not establish physical branch identity or completeness.','foundationPeneloux1982'),
'ch04':('The decline cumulative-volume derivative and pressure/unit relations are checked independently. The reservoir objects demonstrate a lumped inventory/API boundary; they do not validate spatial reservoir sweep or commercial reserves. The P/Z interpretation is restricted to its closed, isothermal volumetric assumptions, and the Horner extrapolation is distinguished from average pressure in a bounded depleted reservoir.','foundationPRMS2018'),
'ch05':('The completed wellbore trials are checked for finite positive pressure and temperature, material conservation and the upward pressure-loss direction; infeasible imposed-rate trials remain identified. The rod-pump displacement is checked against swept geometry, and the jet-pump example checks pressure and efficiency domains. These reduced lift models do not constitute a coupled power-fluid, reservoir and surface design; the Turner coefficient is separately checked for its stated unit convention.','turner1969'),
'ch06':('The compact, supported gas-network example supplies the accepted hydraulic case: four choke openings converge with pressure residual below 100 Pa, mass residual below 10⁻⁶ kg/s and valid pressure/flow directions. Its larger legacy multiphase API candidates remain explicitly unaccepted when hydraulics do not converge. The WellFlow example checks the declared drawdown and bottomhole-pressure constraints; neither solver convergence nor a software constraint authorizes operation beyond field limits.','neqsim2026update'),
'ch07':('The completed subsea pipe/cooler calculations are checked for material conservation and valid pressures and temperatures. The thermal example states its chosen overall heat-transfer coefficient; the audit does not calibrate heat loss, multiphase holdup or vendor equipment performance. Published operator reports distinguish the actual Åsgard, Gullfaks and Vigdis technologies and startup dates; cost and casing factors are explicitly screening inputs.','foundationAsgard2015,foundationGullfaks2015,foundationVigdis2021'),
'ch08':('The completed route calculations are checked for mass/component conservation, positive profile states and pressure-loss direction. The fixed-property thermal characteristic length is independently checked by dimensional analysis; the NeqSim thermal closure itself is not independently calibrated here. Correlation accuracy requires matched measurements, and a gravity/friction comparison is not treated as a sufficient slack-flow or slugging criterion.','beggs1973'),
'ch09':('The hydrate results are screened for finite temperature and the expected direction of MEG inhibition. Hammerschmidt concentration/depression conversions are checked against the corrected SI constant, while solid formation, deposition kinetics, corrosion and erosion require model-specific calibration beyond these examples. Phase equilibrium and a finite onset do not imply a safe shutdown time or an inhibitor guarantee.','foundationGPSAerrata,deboer1995'),
'ch10':('The separation cases are checked for total/component mass and steady-state enthalpy closure, including the explicit free-water outlet. Souders–Brown service factors and residence-time choices are declared screening assumptions; they are not inferred vendor guarantees. Horizontal droplet settling is assessed through residence time and settling distance rather than by comparing perpendicular velocity components.','campbell2014'),
'ch11':('The accepted reboiled columns use an explicit heat input and satisfy the strict numerical column status, MESH residual, stage/boundary mass and energy checks, and phase-fugacity checks. They illustrate the selected stripping conditions, not an unmeasured product specification. Bubble-pressure calculations are labeled TVP; a Reid vapor-pressure claim requires the stated test-method basis.','foundationASTMD3232026'),
'ch12':('The once-through TEG absorber and bounded NGL stabilizer satisfy column/stage material, energy and equilibrium residual checks; regeneration is outside their stated boundaries. The amine calculation instead prescribes removal, conserves transferred components and checks solvent loading, with the original undersized solvent case explicitly rejected. Its isothermal cooling is a required boundary duty, not an independent reactive-absorber energy prediction. Dry-gas JT cases place pretreatment upstream of the illustrated boundary.','neqsim2026update'),
'ch13':('The process-unit examples are checked for material/enthalpy consistency. Salt mass-fraction conversion and the limiting-reactant barite inventory are independently checked; supersaturation and an inventory upper bound do not predict deposited scale or treatment kinetics. The OSPAR statement is tied to the flow-weighted monthly performance standard and its reference analytical method, with site-permit conditions separate.','foundationOSPAR2023,foundationOSPARmethod'),
'ch14':('The solved compressor cases are checked for positive compression work and mass/component/enthalpy closure; the optimizer is checked for returned numerical feasibility. The equal-pressure-ratio result is independently tested only for its equal-efficiency, perfect-intercooling ideal-gas limit. Generated charts and software utilization ratios remain synthetic design aids until matched to the actual gas basis and vendor performance envelope.','schultz1962,foundationNASAcompression'),
'ch15':('The operating compressor examples have mass, energy and state-domain checks. The plotted map curves are explicitly synthetic and are useful for illustrating speed/head/efficiency relationships; their surge and choke boundaries are not a qualified compressor map. Mechanical-speed, gas-property and driver constraints require the corresponding vendor and installation data.','schultz1962'),
'ch16':('The exchanger examples are checked for hot/cold energy closure and feasible terminal temperatures. A separate shifted-temperature heat cascade reproduces the stated pinch utility targets for the supplied constant heat-capacity streams; this verifies the calculation, not the plant stream data or exchanger network layout. Airflow and seawater sizing retain their explicit heat-capacity and approach assumptions.','neqsim2026update'),
'ch17':('The valve calculations are checked for mass/component conservation, isenthalpic throttling and nonnegative pressure drop. Flow-coefficient constants are tied to the specified flow, pressure, temperature and molecular-weight units; operating mode is set explicitly before using coefficient/opening to predict pressure. Relief-area arithmetic does not replace a complete relief-scenario, discharge-system or code assessment.','emerson2023valves'),
'ch18':('The package turbine example checks heat-rate/efficiency identities and the finite ambient-derating trend, while its map and exhaust recipe remain assumed. The accepted backpressure steam example checks recovered duty and shaft-work closure; the failed condensing candidate is retained as a rejection. The electrical bus conserves supply/served/unserved demand, and methane-slip accounting conserves carbon on one fuel and uptime basis.','foundationNASAcompression,foundationNorwayTax2026')}
for p in sorted((B/'chapters').glob('ch*/chapter.md'))[:18]:
 ch=p.parent.name[:4];t=p.read_text(encoding='utf-8')
 start='<!-- foundations-scientific-verification -->';end='<!-- /foundations-scientific-verification -->'
 t=re.sub(re.escape(start)+r'.*?'+re.escape(end)+r'\n*','',t,flags=re.S)
 body,cites=notes[ch]
 section='\n'+start+'\n\n### Verification of the worked examples\n\n'+body+'\\cite{'+cites+'}\n\nThe calculation and literal-code records are in `verification/scientific_revision/'+ch+'_manuscript_physics.json`; the chapter scope and code hashes are indexed in `foundations_review.json`.\n\n'+end+'\n\n'
 m=re.search(r'^##[^\n]*(?:Exercises|Problems|References)\b',t,re.M)
 t=t[:m.start()]+section+t[m.start():] if m else t+'\n'+section
 # Editorial repairs apply only to prose outside code, math, citations and links.
 protected=re.compile(r'(```.*?```|`[^`\n]*`|\$\$.*?\$\$|\$[^$\n]*\$|!?\[[^\]]*\]\([^)]*\)|\\cite\w*\{[^}]*\})',re.S)
 segments=protected.split(t)
 for i in range(0,len(segments),2):
  segments[i]=re.sub(r'\b(the|at|in|for|of|a|an|and|with|than|from|only|about|assumed|generic|universal|below|above|over|under|between|by|to|per|Scope)(?=\d)',r'\1 ',segments[i])
  segments[i]=re.sub(r'(\d)(?=(?:year|years|stage|stages|tray|trays|bara|bar|kg|mol|km|MW|kW|wt|ppm|Pa|µm|mm|NOK)\b)',r'\1 ',segments[i])
 p.write_text(''.join(segments),encoding='utf-8')
(B/'verification/scientific_revision/foundations_chapter_notes.json').write_text(json.dumps({k:{'text':v[0],'citations':v[1].split(',')} for k,v in notes.items()},indent=2),encoding='utf-8')
