"""Finish current subsea/gas-treatment factual and dimensional corrections."""
from revise_foundations_science_phase3 import R,S
S('ch07','hydraulic_response',r'Umbilical design is critical for long tieback distances\. The hydraulic response time.*?shutdown response times\.',r'''Hydraulic pressure-wave propagation and actuator response are different quantities. The first scales roughly as $L/a$ using the wave speed of the fluid/tube system. Filling, draining, line compliance, fluid viscosity, restrictions and actuator volume govern the much longer stroke/charging time. Local accumulators and subsea control logic can supply the required action without waiting to charge the complete long line. Determine shutdown time from the actual actuator/control circuit and barrier function.''')
S('ch07','hydraulic_supplies',r'- \*\*Hydraulic power\*\* — low-pressure.*?on each tree\.', '- **Hydraulic power** — separate pressure circuits serve the qualified actuator functions. Many production valves use hydraulic opening and spring closure; do not assume an HP supply universally powers fail-safe closure. Verify spring/accumulator energy, ambient pressure compensation, leakage and loss-of-supply behavior for each function.')
R('ch07','production_wing_role','the production wing valve (PWV) is the main flow control valve during normal operations','the production wing valve (PWV) provides isolation; normal throttling is performed by the production choke')
R('ch07','boosting_history','Subsea boosting has been commercially proven on multiple Norwegian Continental Shelf (NCS) fields including Åsgard (2015), Gullfaks (2015), and Vigdis (2007).',r'Vigdis multiphase pumping started in May2021. Åsgard and Gullfaks started different subsea compression technologies in2015; they should not be listed as equivalent pump deployments.\cite{foundationVigdis2021,foundationGullfaks2015}',sources=['https://www.equinor.com/news/archive/20210806-giving-vigdis-boost','https://www.equinor.com/news/archive/2015/10/12/12OctGullfakssubseacompression'])
S('ch07','dry_wet_compression',r'Subsea wet gas compression is the most technically challenging.*?300 m water depth\.',r'Åsgard began subsea gas compression in September2015 with gas/liquid separation before compression. Gullfaks began wet-gas compression in October2015 without that upstream phase separation. Their different liquid-handling architectures determine compressor qualification and auxiliary equipment. Åsgard phase2 was completed in2025.\cite{foundationAsgard2015,foundationGullfaks2015,foundationAsgard2025}',sources=['https://www.equinor.com/news/archive/2015/09/17/17SepAasgardsubsea','https://www.equinor.com/news/archive/2015/10/12/12OctGullfakssubseacompression','https://www.equinor.com/news/20250926-phase-2-asgard-subsea-compression'])
S('ch07','TRL_stale',r'The maturity of subsea processing technologies varies:.*?fully qualified and deployed\)\*', 'Technology qualification applies to a specific design and operating envelope. Use a dated qualification dossier and field-reference list; counts and generic TRLs for an entire technology family can hide differences in pressure, fluid, power, intervention and duty. The dated operator examples above establish deployment history, not blanket qualification for a new field.')
S('ch12','water_content_formula',r'The water content of saturated gas at temperature.*?(?=### 12\.2\.2)',r'''A useful low-pressure ideal-gas limit over liquid water is $y_w\simeq a_w P_w^{sat}(T)/P$, with both pressures in the same units. Convert mole fraction to a standard-volume mass concentration using

$$C_{w,sc}=y_w\frac{P_{sc}M_w}{Z_{sc}RT_{sc}}.$$

With $M_w$ in kg/mol and SI pressure, this gives kg/Sm³; multiply by10⁶ for mg/Sm³. At30°C, $P_w^{sat}\simeq4.24$kPa and70bara give about460mg/Sm³ at15°C/1.01325bara when $a_w=Z_{sc}=1$. This ideal limit is not a high-pressure natural-gas prediction: fugacity, dissolved-gas effects and salinity require the selected water model. State the contract pressure and standard-volume basis for any gas-water specification.

''')
S('ch12','TEG_dewpoint_unsupported',r'The equilibrium water dew point over a TEG solution can be correlated.*?(?=### 12\.2\.3)',r'''The solvent water activity fixes the equilibrium water fugacity at the contactor temperature and pressure. Lower lean-TEG water content usually lowers the attainable gas-water content, but a dew-point value also requires the downstream pressure and dew-point phase convention. A pressure-free TEG-purity/dew-point table is therefore not a usable design relation. Calculate the equilibrium limit at the stated conditions, then account for finite contacting efficiency and circulation. The checked once-through example later in this chapter states mass fraction, stages, feed state and circulation explicitly; regeneration feasibility is a separate calculation.

''')
R('ch12','sieve_BTEX','| BTEX emissions | Yes (from regeneration) | No |','| BTEX handling | Coabsorption can release aromatics in regenerator overhead | Coadsorbed hydrocarbons can appear in regeneration gas |')
S('ch12','sieve_necessary',r'For cryogenic NGL recovery plants using turboexpanders, molecular sieve dehydration is mandatory.*?heat exchangers\.', 'Cryogenic service requires a verified water specification over the coldest temperature/pressure path. Molecular sieves are commonly selected for deep dehydration; a universal1ppmv freezing threshold is incorrect because ice/hydrate stability depends on fugacity and operating conditions.')
S('ch12','mercury_cracking',r'causing stress-corrosion cracking.*?no warning','potentially causing liquid-metal embrittlement and amalgamation-related damage. This mechanism is distinct from conventional aqueous stress-corrosion cracking')
R('ch12','mercury_free_energy',r' \quad (\Delta G^0 = -50.6 \text{ kJ/mol})','')
S('ch12','membrane_product',r'However, membrane systems have lower methane recovery.*?potential emissions concern\.', 'Methane recovery depends on membrane selectivity, stage cut and recycle. In the methane-selective arrangement just described, methane-rich permeate is the product and unrecovered methane remains in the nitrogen-rich retentate. Assess both streams and their downstream use; do not label the product permeate as the loss stream or assume an untreated stream may be vented.')
