"""Recorded scientific corrections to the optimization theory and framework text."""
import json
import re
from pathlib import Path

BOOK = Path(__file__).resolve().parents[1]
OUT = BOOK / 'verification/scientific_revision'
CHANGES = []

def edit(n, pairs):
    path = next((BOOK/'chapters').glob(f'ch{n:02d}_*/chapter.md'))
    original = path.read_text(encoding='utf-8-sig')
    backup = BOOK/'.build/backups/scientific_revision'/path.parent.name/'framework_input.md'
    backup.parent.mkdir(parents=True, exist_ok=True)
    if not backup.exists():
        backup.write_text(original, encoding='utf-8')
    text = backup.read_text(encoding='utf-8')
    for old, new in pairs:
        if old not in text:
            raise AssertionError(f'ch{n}: {old[:120]}')
        text = text.replace(old, new)
        CHANGES.append({'chapter': n, 'before': old, 'after': new})
    markers = lambda t: re.findall(r'<!-- reviewed-notebook-results:start -->.*?<!-- reviewed-notebook-results:end -->',t,re.S)
    assert markers(text) == markers(original)
    path.write_text(text, encoding='utf-8')

edit(23, [
('Every process simulator can solve a fixed problem:', 'A process simulator is commonly used to solve a fixed problem:'),
('Conversely, a process simulator knows its equipment intimately but has no built-in optimizer.', 'A simulator may also include optimization tools, but the search still needs explicit decisions, objectives and acceptance criteria.'),
('the `CapacityConstrainedEquipment` interface that endows every equipment unit with knowledge of its own operating limits', 'the `CapacityConstrainedEquipment` interface that exposes configured limits for participating equipment'),
('and respect all constraints', 'and evaluate the constraints explicitly included in the model'),
('Earlier chapters have introduced optimization theory (Chapter 22) and production optimization workflows (Chapter 24).', 'Chapter 22 introduces optimization theory; Chapter 24 develops the production workflow.'),
('changing the feed rate affects all downstream equipment monotonically.', 'changing the feed rate affects downstream equipment, but monotonic feasibility must be checked across the chosen bounds.'),
('Linear topologies favor `BINARY_FEASIBILITY` or `GOLDEN_SECTION_SCORE` for speed.', 'Use binary feasibility only after establishing a monotonic feasible interval, and golden-section only for a unimodal score; linear topology alone establishes neither property.'),
('Gate every optimizer trial on the single `feasible` flag', 'Use the `feasible` flag as the API acceptance gate, then independently check the required physical balances, product constraints and declared capacity coverage'),
('Equipment trip or failure; optimizer treats as infeasible', 'Configured acceptance limit; violation is infeasible, but this flag does not simulate a trip'),
('Optimizer penalizes but may accept; efficiency reduced', 'May be penalized; no automatic physical efficiency reduction follows from the label'),
('Calling `autoSize()` without arguments uses a default safety factor of 1.0 (design = current), which is useful for modeling existing equipment with known nameplate capacity.', 'Defaults and sizing calculations are equipment-specific. Discover the resulting dimensions, chart state, design values and enabled constraints after sizing. Existing equipment requires its actual ratings; an inferred design point is not nameplate evidence.'),
('These presets load constraint parameters from reference data (design codes, company technical requirements) rather than computing them from current conditions. This is appropriate when modeling existing facilities where the design-basis constraints are known from the original equipment datasheets.\n\nThe preset mechanism reads from CSV design data files (`TechnicalRequirements_Process.csv`) stored in the NeqSim resources directory. Engineers can extend these files with additional company standards or equipment-specific overrides. This data-driven approach means that constraint values can be updated without modifying Java code — a significant advantage for multi-asset operations where different facilities may follow different design standards.', 'These convenience presets enable selected constraints. They do not establish compliance with a company standard or import an installed-equipment rating merely because the method name mentions that standard. Inspect every enabled constraint and explicitly configure ratings from the applicable design basis. Mechanical-design database lookups are a separate workflow.'),
('**Table 23.1.** Capacity constraints by equipment type.', '**Table 23.1.** Engineering checks to consider by equipment type. This is a checklist, not a promise that every listed check is created automatically; discover the actual registered constraint names and coverage.'),
('The optimizer also identifies the **knee point** — the Pareto-optimal solution with the best balance between objectives.', 'The engineer must select a preferred point using declared economic or operational preferences. The current `ParetoResult` exposes the front, utopia and nadir points; it does not provide an automatic knee-point method. A finite weighted-sum sweep can miss unsupported portions of a non-convex front.'),
('**generateLiftCurve()** — Sweeps over arrays of pressures, temperatures, water cuts, and GORs to generate a multi-dimensional lift curve:', '**generateCapacityScreening()** — Sweeps supported pressure and temperature axes for a fixed composition to calculate a mass-throughput screening table:'),
('The lift curve is a tabulated response surface that maps operating conditions to maximum throughput — the same data used for production optimization in reservoir simulation models.', 'This table maps declared process boundaries to a screened maximum mass throughput. It is not a well VFP table: a reservoir export requires independently solved BHP values, a datum and phase-volume bases. The legacy composition arguments accept only singleton zero placeholders at this source revision.'),
('with 18 built-in strategies', 'with registered built-in strategies'),
('This integration means the optimization respects not just the compressor\'s rated limits but its actual performance characteristics at any operating point — a level of fidelity that is essential for accurate production optimization in gas-dominated systems.', 'The integration evaluates the supplied map. A generated map remains an assumed screening model; installed performance requires vendor or measured curves, gas-property corrections and a verified operating envelope.'),
('The templates are based on published correlations for centrifugal compressor performance and can serve as reasonable approximations for concept-level studies.', 'These templates provide assumed curve shapes for concept-level sensitivity studies; this chapter does not validate them against a particular compressor.'),
('These corrections improve the fidelity of the performance map at operating points far from the design condition, which is precisely where the optimizer explores during throughput maximization.', 'Corrections are model options whose applicability must be checked against measured or vendor data. Extrapolation away from the reference map is not validated by enabling them.'),
('A flowsheet behind `evaluate()` is a noisy, feasibility-gated black box with no usable analytic gradient, so a derivative-free method is the appropriate choice.', 'A flowsheet behind `evaluate()` can be treated as a feasibility-gated black box. Derivative-free search is one option; finite-difference or analytic sensitivities can be preferable when the model is smooth and reproducible.'),
('Hard constraints are folded into the objective as weighted quadratic penalties:', 'Address-based constraints enter the score as weighted quadratic penalties; finite penalties alone are not hard feasibility guarantees:'),
('the global-optimum guarantee is `partial`;', 'the readiness JSON describes global-search capability as `partial`, but this is not a mathematical guarantee of a global optimum;'),
('`maxUtilization` (0\\u20131)', '`maxUtilization` (dimensionless and possibly greater than one)'),
('Pareto front generation with knee-point detection supports decision-making under competing objectives.', 'Sampled Pareto fronts support an explicit preference-based decision; no unique knee need exist.'),
('integration ensures that compressor-limited systems are optimized with full performance-map fidelity', 'integration evaluates the supplied compressor-map model'),
('Plot the Pareto front and identify the knee point.', 'Plot the sampled front, state the objective scaling and test whether a defensible knee exists.'),
])

edit(24, [
('# Chapter 18: Production Optimization', '# Production Optimization'),
('Sections 18.', 'Sections 24.'),
('–18.', '–24.'),
('**Example**: A platform producing 100,000 bbl/day of oil at $70/bbl generates $7M/day. A 2% production increase through optimization yields an additional $51M/year — far exceeding the cost of implementing an optimization system.\n\nIndustry studies report typical optimization gains of:\n- 1–3% throughput increase through separator pressure optimization\n- 2–5% through gas lift allocation optimization\n- 3–8% through debottlenecking guided by constraint analysis\n- 5–15% through comprehensive facility-wide optimization', '**Illustrative gross-revenue calculation:** at an assumed 100,000 bbl/day, 70 USD/bbl, 365 operating days and a hypothetical 2% uplift, incremental revenue is 51.1 million USD/year. This is not a measured optimization benefit or net project value. Subtract incremental operating cost, capital, downtime and applicable fiscal charges before judging an investment. No generic percentage uplift is established by this example.'),
('The equipment with the highest utilization factor is the **bottleneck** — it limits the overall system throughput:', 'The highest reported utilization identifies a candidate limiting check. Only when each relevant load scales linearly with feed and its limit remains fixed does the following approximate throughput extrapolation apply:'),
('where $A_{\\text{gas}}$ is the cross-sectional area available for gas flow. For a horizontal separator with liquid occupying fraction $f = h/D$ of the diameter, the gas area is:\n\n$$\nA_{\\text{gas}} = \\frac{\\pi D^2}{4} \\cdot (1 - f)\n$$', 'where $A_{\\text{gas}}$ is the free gas cross-section. For a horizontal cylinder, liquid height fraction is not area fraction. With radius $r=D/2$ and height $0\\le h\\le D$,\n\n$$\n\\begin{aligned}\nA_L(h)&=r^2\\cos^{-1}\\!\\left(\\frac{r-h}{r}\\right)\n -(r-h)\\sqrt{2rh-h^2},\\\\\nA_{\\text{gas}}&=\\pi r^2-A_L(h).\n\\end{aligned}\n$$\n\nThe simple half-area result holds at $h=D/2$; apply the segment geometry elsewhere.'),
('The coefficient depends on separator type and internal devices:', 'The coefficient depends on device loading, droplet size, pressure and fluid properties. The following broad classroom ranges are not vendor guarantees or design-code limits:'),
('Typical minimum retention times:', 'Illustrative retention-time ranges, requiring fluid-specific settling/coalescence evidence:'),
('where $\\sigma_{\\text{GL,max}} \\approx 0.005$–$0.015$ m³/m²·s depending on oil API gravity and GOR.', 'The admissible interface loading requires a stated disengagement model or test basis. No universal value follows from API gravity and GOR alone.'),
('Below surge, flow reversal causes severe mechanical damage at 1–10 Hz cycles.', 'Surge can cause oscillatory flow reversal and damage; its frequency depends on the compressor and connected volumes.'),
('\\frac{Q_{\\text{actual}} - Q_{\\text{surge}}}{Q_{\\text{actual}}}', '\\frac{Q_{\\text{actual}} - Q_{\\text{surge}}}{Q_{\\text{surge}}}'),
('A typical minimum surge margin is 10%.', 'A 10% margin is an assumed teaching value on this surge-flow denominator basis; use the vendor/controller definition and requirement.'),
('Centrifugal compressor tip speeds above ~350 m/s risk mechanical failure.', 'Use the manufacturer\'s mechanical speed limit; tip speed alone does not define a universal failure threshold.'),
('Typical limit: 150–180°C for dry gas seals.', 'Use the applicable seal, material and lubricant temperature limits; no universal dry-gas-seal limit is implied.'),
('Q = N_1 \\cdot F_L \\cdot C_v \\cdot \\sqrt{\\frac{\\Delta P}{\\rho / \\rho_0}}', 'Q = N_1 F_P C_v \\sqrt{\\frac{\\Delta P_{\\mathrm{sizing}}}{\\rho/\\rho_0}}'),
('W = N_6 \\cdot F_{\\gamma} \\cdot C_v \\cdot Y \\cdot \\sqrt{x \\cdot P_1 \\cdot \\rho_1}', 'W = N_6 F_P C_v Y \\sqrt{x_{\\mathrm{sizing}}P_1\\rho_1}'),
('where $Y = 1 - x/(3 x_T)$ is the expansion factor, $x = \\Delta P / P_1$ is the pressure drop ratio, and $x_T$ is the critical pressure drop ratio for the valve.', 'Here $F_P$ is the piping geometry factor, $x=\\Delta P/P_1$, $x_{\\mathrm{sizing}}=\\min(x,F_\\gamma x_{TP})$, and $Y=1-x_{\\mathrm{sizing}}/(3F_\\gamma x_{TP})$. For liquid service use the lesser of the actual and liquid-choking pressure drop; recovery factor $F_L$ belongs in that choking calculation, not as a general multiplier on subcritical flow. The constants $N_1,N_6$ depend on the stated unit system. See the manufacturer sizing procedure \\cite{emerson2023valves}.'),
('The valve opening utilization compares required $C_v$ to installed $C_v$:', 'A coefficient-capacity ratio compares required $C_v$ to maximum installed $C_v$:'),
('Good control practice requires operation between 20% and 80% valve opening.', 'The coefficient ratio is not travel unless the installed characteristic is linear. A 20–80% travel window is an illustrative control-authority assumption, not a universal requirement.'),
('For choke valves in well service, the flow equation includes critical flow effects and multiphase corrections:\n\n$$\nC_{v,\\text{required}} = \\frac{Q_{\\text{total}}}{\\sqrt{\\Delta P / \\rho_m}} \\cdot F_{\\text{multiphase}}\n$$\n\nThe $F_{\\text{multiphase}}$ correction accounts for flashing, two-phase flow, and gas release, and can be 1.2–2.5 times larger than the single-phase $C_v$ requirement.', 'For well-service chokes, use a named multiphase/choked-flow model with a defined phase-volume basis and calibrated discharge coefficient. A single arbitrary multiplier on a single-phase $C_v$ expression does not establish flashing or critical-flow capacity.'),
('The mixture velocity must not exceed the erosional velocity limit to prevent pipe wall erosion:', 'An empirical velocity screen can flag a need for further assessment; satisfying it does not establish freedom from erosion, corrosion or sand damage:'),
('For multiphase flow, flow-induced vibration is assessed using the DNVGL RP-F101 criteria:', 'For multiphase flow, vibration assessment must include excitation, support stiffness, geometry and fatigue response. DNV-RP-F101 addresses corroded pipelines, not vibration screening. The following normalized indicators are illustrative only; apply the relevant Energy Institute guidance or another explicitly qualified method \\cite{dnvf101scope,eivibration}: '),
('\\frac{dP}{dL} = \\frac{f \\rho_m v_m^2}{2D} + \\rho_m g \\sin\\theta + \\rho_m v_m \\frac{dv_m}{dL}', '-\\frac{dP}{dL} = \\frac{f_D \\rho_f v_m^2}{2D} + \\rho_h g \\sin\\theta + \\rho_a v_m \\frac{dv_m}{dL}'),
('**MAOP**: The Maximum Allowable Operating Pressure is a regulatory/design limit that cannot be exceeded under any conditions.', 'The coordinate follows the flow, with positive inclination uphill. The schematic momentum equation distinguishes holdup density $\\rho_h$ from friction/acceleration effective densities; Beggs–Brill applies its own holdup and slip correlations.\n\n**MAOP**: enforce the applicable operating pressure limit and separately assess the design code\'s transient/protection requirements.'),
('\\text{NPSH}_A = \\frac{P_{\\text{suction}} - P_{\\text{vapor}}}{\\rho g} + \\frac{v^2}{2g} + z_{\\text{suction}}', '\\text{NPSH}_A = \\frac{P_{s,\\mathrm{abs}}-P_v}{\\rho g}+\\frac{v_s^2}{2g}'),
('The NPSH margin should be at least 10–20% ($U_{\\text{NPSH}} < 0.83$–$0.90$) to account for transients and instrument uncertainty.', 'Pressure and velocity here are at the suction flange on the pump reference datum; an elevation term is added only when converting from another measurement datum. Required NPSH commonly denotes a specified head-drop test criterion, not zero cavitation. Set the application-specific margin using the pump vendor and applicable guidance.'),
('W_{\\text{pump}} = \\frac{Q \\cdot \\Delta P}{\\eta_{\\text{pump}} \\cdot \\eta_{\\text{motor}}}', 'W_{\\text{electrical}} = \\frac{Q \\Delta P}{\\eta_{\\text{pump}} \\eta_{\\text{motor}}}'),
('\\frac{W_{\\text{pump}}}{W_{\\text{driver,max}}}', '\\frac{Q\\Delta P/\\eta_{\\text{pump}}}{W_{\\text{driver,shaft,max}}}'),
('U_{\\text{foul}} = \\frac{U_{\\text{clean}}}{U_{\\text{clean}} - R_f \\cdot U_{\\text{clean}}^2} \\cdot \\frac{1}{A \\cdot \\Delta T_{\\text{LMTD}}} \\cdot Q_{\\text{required}}', '\\frac{1}{U_{\\mathrm{fouled}}}=\\frac{1}{U_{\\mathrm{clean}}}+R_f, \\qquad\nU_{\\mathrm{duty}}=\\frac{Q_{\\mathrm{required}}}{U_{\\mathrm{fouled}}A\\Delta T_{\\mathrm{LMTD}}F_t}'),
('if the approach temperature is too small, the exchanger is oversized relative to the need; if too large, it may be undersized.', 'a small positive approach leaves little thermal driving force and may require large area. A large approach alone does not diagnose undersizing; compare duty and both stream energy balances. Check both terminal differences and internal pinch points when heat capacity or phase state varies.'),
('When `objectives` is null, the optimizer maximizes the feed stream flow rate.', 'With no explicit objectives, score-based modes have zero objective score. Rate-only `BINARY_FEASIBILITY` still seeks the highest feasible rate; supply an objective for all score-based searches.'),
('O(\\log_\\phi((b-a)/\\text{tolerance}))', 'O(\\log_{1/\\phi}((b-a)/\\text{tolerance}))'),
('Smooth, convex problems with many variables', 'Smooth, concave maximization scores with several variables'),
('Global | Convergence', 'Global guarantee | Convergence'),
('| PARTICLE_SWARM_SCORE | 1–20 | Yes | Yes |', '| PARTICLE_SWARM_SCORE | 1–20 | Yes | No |'),
('This analysis directly answers the debottlenecking question: *Which equipment upgrade provides the largest production increase per unit of investment?*', 'This sensitivity identifies local production effects under the model assumptions. Investment ranking additionally requires upgrade costs, interactions and independently replayed feasible cases.'),
('The lift curve shows how facility capacity varies with inlet conditions — this is the "facility back-pressure curve" that can be intersected with the reservoir inflow performance relationship (IPR) to find the stable operating point.', 'The table shows screened mass capacity at fixed composition and declared inlet conditions. It is not a bottomhole-to-wellhead hydraulic relation, and intersection with an IPR alone does not establish a coupled stable well solution.'),
('The lift curve generated by `ProcessOptimizationEngine` can be used to create Vertical Flow Performance (VFP) tables for reservoir simulators like Eclipse or IX:', 'Reservoir VFP export requires a separately solved, complete BHP grid and consistent datum/phase-volume axes. Generic process-capacity screening cannot be directly exported as VFP:'),
('This creates a two-way coupling between the reservoir and facility models, enabling integrated production optimization across the full production system.', 'A complete coupling must additionally solve the well hydraulics and match each exchanged pressure and phase rate at the same physical boundary.'),
('the exchange rate is 0.2 MW per 10,000 kg/hr.', 'the exchange rate is 2 MW per 10,000 kg/hr, or 0.2 kWh/kg.'),
('The knee point represents the best compromise', 'A knee, if present under a stated normalization, is one possible compromise'),
('SM = 1 - \\frac{Q_{surge}}{Q_{operating}} \\geq SM_{min}', 'SM = \\frac{Q_{operating}-Q_{surge}}{Q_{surge}} \\geq SM_{min}'),
('with $SM_{min}$ typically 10-15% per API 617.', 'with $SM_{min}$ specified by the vendor/control design on this denominator basis; a universal 10–15% API requirement is not established here.'),
('Heavier gas at lower reservoir pressure requires more head per stage, pushing the compressor toward surge at the same volumetric flow.', 'At fixed pressure ratio and inlet temperature, increasing molecular weight generally reduces specific compression head in the constant-property expression; declining suction pressure increases the pressure ratio. These competing effects and the corrected map must be evaluated together.'),
('The affinity laws relate off-design performance to the design point:', 'The affinity laws approximate dynamically similar points with unchanged geometry and inlet density; compressible Mach/Reynolds and gas-property effects limit their application:'),
('For common operational scenarios, NeqSim provides preset configurations that pre-populate equipment constraints with industry-standard values:', 'Convenience presets enable selected configured checks; they do not certify industry-standard values or installed equipment ratings:'),
('These presets encode operational experience: gas turbines lose approximately 0.5-0.7% power output per degree Celsius above ISO conditions (15 °C), so summer ambient temperatures of 30 °C can derate a gas turbine by 8-10%.', 'Ambient derating must be supplied from the actual driver map. A preset name does not create that map or qualify a seasonal power allowance.'),
('- Better water settling → less water in oil', '- Water settling must be evaluated from density difference, viscosity, droplet distribution and residence time; its direction is not determined by pressure alone'),
('- More light ends in gas → higher gas heating value', '- The resulting gas composition determines heating value; the direction must be calculated on a common reference basis'),
('Optimization is only meaningful when the process is at or near steady state. Transient conditions (slug flow, well startup, separator level cycling) produce meaningless optimization results.', 'Steady-state RTO requires sufficiently settled data for its model. Dynamic optimization can treat transients explicitly when the dynamic model and constraints are qualified; transient data are not suitable inputs to an unmodified steady-state reconciliation.'),
('Norway\'s petroleum tax system penalizes flaring through a CO₂ tax of approximately 1,000 NOK/tonne ($100/tonne), making flaring reduction directly profitable.', 'Use dated, jurisdiction-specific tax and allowance prices when valuing emissions; this chapter does not supply a current fiscal tariff.'),
('The World Bank\'s Zero Routine Flaring initiative targets elimination of routine flaring by 2030.', 'The voluntary World Bank Zero Routine Flaring initiative targets routine oil-production flaring by 2030; it distinguishes routine disposal from safety and other non-routine events \\cite{worldbankzrf}.'),
('When the gas compressor is the bottleneck, the zero-flare production rate is typically 15-25% below the mechanical maximum. The optimizer quantifies this trade-off precisely, allowing operators to make informed decisions about flare versus production.', 'The production cost of a no-routine-flaring constraint is case-specific. Calculate it with the full gas balance and available recovery/export routes; no generic 15–25% loss is established here.'),
('Recommended utilization limits by equipment type:', 'Illustrative screening margins by equipment type. These are not operating permissions; establish applicable ratings and transient allowance independently:'),
('| Single variable, non-monotonic | GOLDEN_SECTION_SCORE |', '| Single variable, unimodal score | GOLDEN_SECTION_SCORE |'),
('- Relax utilization limits', '- Check the ratings and bounds; change a limit only when its engineering basis supports the change'),
('simulating an upgrade', 'forming an unconstrained screening counterfactual'),
('Calculate the percentage throughput increase from the upgrade.', 'Report this as an upper-bound counterfactual. Then specify a finite upgraded rating and replay all constraints before claiming an upgrade benefit.'),
])

OUT.mkdir(parents=True, exist_ok=True)
(OUT/'framework_corrections.json').write_text(json.dumps(CHANGES, indent=2, ensure_ascii=False), encoding='utf-8')
print(f'Applied {len(CHANGES)} recorded corrections')
