"""Scientific review corrections: produced water, compression, heat and power."""
from revise_foundations_scientific_text import revise, BOOK, ledger
import re, json, math

def R(ch, key, old, new, issue=None, sources=None):
    revise(ch, ch+'_'+key, old, new, issue or key.replace('_',' '), sources or ['Dimensional analysis and conservation-law derivation; reviewed against the cited chapter references'])

def S(ch, key, pattern, new, issue=None, sources=None):
    if any(x['id']==ch+'_'+key for x in ledger): return
    text=next((BOOK/'chapters').glob(ch+'*/chapter.md')).read_text(encoding='utf-8')
    m=re.search(pattern,text,re.S)
    if not m: raise ValueError(ch+'_'+key)
    R(ch,key,m[0],new,issue,sources)

S('ch13','production_totals',r'For every barrel of oil produced globally,.*?per year\.', 'Produced-water volumes depend strongly on field age, reservoir connectivity and injection strategy; global water-to-oil ratios and annual NCS totals require a dated inventory and are not design inputs for an individual facility.')
S('ch13','brine_density',r'The density of produced water increases with salinity.*?density of the salt species\.',r'''Brine density depends on temperature, pressure and dissolved composition. The previous molecular-weight/solid-density expression is dimensionally unsuitable for a solution. Calculate density from a validated electrolyte property model or measured brine data. For converting a measured salt concentration to mass fraction, the exact definition is

$$w_s=\frac{C_s}{\rho_{\mathrm{brine}}}$$

with both $C_s$ and $\rho_{\mathrm{brine}}$ in kg/m³; 1 mg/L = 0.001 kg/m³. For example, 100,000 mg/L in brine of density 1,070 kg/m³ corresponds to $w_s=0.09346$, not 10 wt%. An iterative density/composition calculation may be needed if only TDS is known.''')
R('ch13','ospar_method','The 30 mg/L limit is measured by the reference method ISO 9377-2 (hydrocarbon oil index using GC-FID after solvent extraction). Individual measurements may exceed 30 mg/L provided the monthly weighted average is met:',r'The OSPAR reference is Agreement 2005-15, based on a modified ISO 9377-2 extraction/GC-FID procedure. The 30 mg/L performance standard is a flow-weighted monthly average; site permits can impose additional sample, alarm or discharge-stop conditions.\cite{foundationOSPARmethod} The averaging calculation is:', sources=['https://www.ospar.org/documents?v=32591'])
R('ch13','ospar_oldgoal','**Zero harmful discharge**: OSPAR\'s goal is to achieve zero discharge of hazardous substances by 2020 (aspirational)', '**Hazardous-substance reduction**: apply the current OSPAR strategy and the installation permit; the historical 2020 aspiration is not a current discharge authorization')
S('ch13','cyclone_dimension',r'The cut size \$d_\{50\}\$.*?volumetric flow rate\.',r'''A cut-size correlation must be calibrated for the actual liner geometry and droplet population. A dimensionally consistent relative screening relation for a fixed liner is

$$\frac{d_{50}}{d_{50,0}}\simeq\left[\frac{\mu_w}{\mu_{w,0}}\frac{\Delta\rho_0}{\Delta\rho}\frac{Q_0}{Q}\right]^{1/2}.$$

All ratios are dimensionless. It extrapolates a measured reference cut size rather than predicting an absolute cut size from an undefined geometry constant. Reject split, turbulence-induced breakup and the tested flow envelope also matter.''')
R('ch13','pdr_definition','The ratio of the reject-side pressure drop to the feed-side pressure drop.',r'$\mathrm{PDR}=(P_{\mathrm{feed}}-P_{\mathrm{reject}})/(P_{\mathrm{feed}}-P_{\mathrm{clean}})$.')
R('ch13','gc_not_ir','| IR absorption (ISO 9377-2) | GC-FID after extraction |','| Solvent extraction and gas chromatography (modified ISO 9377-2) | GC-FID after extraction |')
R('ch13','scale_supersaturation','Mineral scale formation occurs when the saturation index (SI) of a mineral exceeds zero.', 'A positive saturation index indicates thermodynamic supersaturation. Precipitation rate and deposition location additionally depend on nucleation, residence time, inhibitors and transport; SI > 0 alone does not establish plugging.')
S('ch13','scale_mass_basis',r'The mixing of formation water and seawater creates.*?mixing fractions of formation water and seawater respectively\.',r'''Scale potential depends on the actual ion inventory, not a universal seawater fraction. With additive water volumes, ion concentrations $C$ in kg/m³ and molecular weights $M$ in kg/mol, a complete-precipitation upper bound is

$$C_{\mathrm{BaSO_4,max}}=M_{\mathrm{BaSO_4}}\min\!\left[\frac{C_{\mathrm{Ba}}(1-f)}{M_{\mathrm{Ba}}},\frac{C_{\mathrm{SO_4}}f}{M_{\mathrm{SO_4}}}\right].$$

The minimum must be taken on a molar basis. For the next example, equal available moles occur at $f=0.0609$ (6.09% seawater), giving about 399 mg/L potential BaSO₄; a 10–90% grid misses this peak. Solubility and precipitation kinetics reduce or redistribute the deposited amount.''')
R('ch13','inevitable_scale','barium sulfate precipitation is virtually inevitable','barium sulfate supersaturation can develop; precipitation must be assessed for the mixed composition and operating path')
S('ch13','scale_policy',r'Based on the severity assessment:\n\n\| Scale Mass.*?virtually eliminating the BaSO₄ scaling risk\.', 'Use the predicted supersaturation and upper-bound precipitate mass to select laboratory compatibility and dynamic deposition tests. There is no universal mg/L threshold below which inhibitor is unnecessary. Compare continuous dosing, squeeze treatment and sulfate-removal options using measured inhibitor performance, residual sulfate, formation-water chemistry and injection history; sulfate removal reduces risk but cannot guarantee zero scale.')
R('ch13','souring_number','### 13.7.2 Souring','### 13.7.4 Souring')
R('ch13','corrosion_number','### 13.7.3 Corrosion','### 13.7.5 Corrosion')
R('ch13','cpa_pressure',r'- \frac{RT}{V_m} \left(\frac{1}{V_m}\frac{\partial \ln g}{\partial (1/V_m)}\right)',r'- \frac{RT}{2V_m} \left[1+\frac{1}{V_m}\frac{\partial \ln g}{\partial (1/V_m)}\right]', 'CPA association pressure omitted the one-half factor and unity term.')
R('ch13','watercut_shape','This exponential sensitivity to water cut','This nonlinear rational dependence on water cut')
R('ch13','stokes_exercise','Use water viscosity of 0.47 cP.', 'Use water viscosity of 0.47 cP. Calculate droplet Reynolds number for each result; replace Stokes drag with an appropriate finite-Re drag relation where creeping flow is not satisfied.')
R('ch13','scale_exercise_grid','(c) At what mixing ratio is the scale mass maximum?', '(c) Derive the continuous mixing fraction for equal available ion moles, and sample that point explicitly; does the coarse grid capture the maximum?')
R('ch14','isentropic_minimum','The minimum work required to compress gas from state 1 to state 2 is the isentropic (reversible, adiabatic) work.', 'For an adiabatic compressor with fixed inlet state and outlet pressure, reversible isentropic compression gives the minimum specific work. Allowing heat rejection changes the comparison; reversible isothermal compression can require less work.')
R('ch14','mw_units','and $MW$ is the gas molecular weight (kg/kmol).','and $MW$ is the molar mass in kg/mol. The result is J/kg; divide by 1,000 for kJ/kg or by $g$ for metres. Inserting $Z_1$ is a constant-property real-gas approximation, not an exact isentropic EOS calculation.')
S('ch14','schultz',r'For real gases at high pressures, the ideal gas relations.*?(?=### 14\.3\.5)',r'''For a real gas, an endpoint Schultz calculation uses an isentropic reference state $2s$ at the discharge pressure. Define specific volume in m³/kg, enthalpy in J/kg and pressure in Pa:

$$n_s=\frac{\ln(P_2/P_1)}{\ln(v_1/v_{2s})},\qquad n_v=\frac{\ln(P_2/P_1)}{\ln(v_1/v_2)}.$$

$$f_s=\frac{h_{2s}-h_1}{[n_s/(n_s-1)](P_2v_{2s}-P_1v_1)},\qquad H_p=f_s\frac{n_v}{n_v-1}(P_2v_2-P_1v_1).$$

The derivative properties $X=(T/v)(\partial v/\partial T)_P-1$ and $Y=-(P/v)(\partial v/\partial P)_T$ assist real-gas analysis, but $Y/(X+1)$ is not the Schultz head factor. Endpoint methods approximate the compression path; verify high-pressure or near-critical cases against a converged small-step calculation and report the selected NeqSim polytropic method.\cite{foundationCCPmethods}

''', sources=['https://ccp-centrifugal-compressor-performance.readthedocs.io/en/stable/references/performance_functions.html'])
R('ch14','eta_domain','The two efficiency definitions are related but not equal:', 'For a calorically perfect ideal gas and constant polytropic efficiency, the two definitions are related by:')
S('ch14','eta_table',r'\| 1\.5 \| 80\.0.*?\| 5\.0 \| 80\.0.*?\|\n', ''.join(f'| {r:.1f} | 80.0 | {100*(r**(.3/1.3)-1)/(r**(.3/(1.3*.8))-1):.2f} | {80-100*(r**(.3/1.3)-1)/(r**(.3/(1.3*.8))-1):.2f} points |\n' for r in [1.5,2,3,4,5]), 'Recalculated ideal-gas efficiency table from its stated gamma and eta.')
R('ch14','polypower',r'\dot{W}_{\text{gas}} = \dot{m} \cdot H_p = \dot{m} \cdot \frac{n}{n-1}',r'\dot{W}_{\text{gas}} = \dot{m} \cdot \frac{H_p}{\eta_p} = \frac{\dot{m}}{\eta_p} \cdot \frac{n}{n-1}', 'Polytropic head must be divided by polytropic efficiency to obtain gas work.')
R('ch14','stage_power_eta',r'\dot{W}_{\text{total}} = N \cdot \dot{m} \cdot \frac{n}{n-1}',r'\dot{W}_{\text{total}} = N \cdot \frac{\dot{m}}{\eta_p} \cdot \frac{n}{n-1}')
R('ch14','intercool_isothermal','by cooling the gas closer to the isentropic path','by reducing specific volume before the next pressure increase; many perfectly intercooled stages approach an isothermal compression path')
R('ch14','equalratio_domain','with perfect intercooling (cooling back to suction temperature):','for the same ideal gas, constant equal stage efficiencies, no sidestreams, negligible interstage pressure loss and perfect intercooling (cooling back to suction temperature):')
S('ch14','relative_power_table',r'\| 4 \| 100%.*?\| 25 \| 100%.*?\|\n', ''.join('| '+str(r)+' | '+ ' | '.join(f'{100*n*(r**(.3/(1.3*.8)/n)-1)/(r**(.3/(1.3*.8))-1):.1f}%' for n in [1,2,3,4])+' |\n' for r in [4,9,16,25]), 'Recomputed stage-power comparison with explicitly eta_p=0.80.')
R('ch14','staging_caption',r'$\gamma = 1.3$, perfect intercooling to inlet temperature.',r'$\gamma = 1.3$, $\eta_p=0.80$, constant properties, no interstage pressure losses and perfect intercooling to inlet temperature.')
R('ch14','api_temp','API 617 limits: typically < 200°C for carbon steel, < 260°C for alloy','The specified maximum continuous discharge temperature, established from gas chemistry, seals, materials and vendor limits; 150°C is an assumed exercise constraint, not a universal API 617 material limit')
R('ch14','heat_rate_units',r'\dot{m}_{\text{fuel}} = \frac{\dot{W}_{\text{shaft}} \times \text{HR}}{LHV}',r'\dot{m}_{\text{fuel}}\,[\mathrm{kg/s}] = \frac{\dot{W}_{\text{shaft}}\,[\mathrm{kW}]\times \mathrm{HR}\,[\mathrm{kJ/kWh}]}{3600\,LHV\,[\mathrm{kJ/kg}]}', 'Heat rate conversion omitted seconds per hour.')
R('ch14','worked_temperatures','the discharge temperatures are approximately 120–135°C — within limits.', 'using 35°C suction for all stages gives approximately 155–168°C. This initial three-stage choice fails the assumed 150°C limit; evaluate four stages or different cooling and pressure splits before accepting a design.')
R('ch14','api_edition','8th ed. American Petroleum Institute.','9th ed. American Petroleum Institute.', sources=['https://www.api.org/-/media/files/publications/2023_catalog/refining-2023.pdf'])
R('ch14','speed_section','(discussed in detail in Chapter 13)','(discussed in detail in Chapter 15)')
S('ch14','vfd_savings',r'The power saving from speed reduction compared to throttling.*?(?=### 14\.13\.2)', 'For dynamically similar points at unchanged density and efficiency, 90%, 80%, 70% and 60% speed give cubic-law power ratios of72.9%,51.2%,34.3% and21.6%. These points also have lower head. A process requiring a fixed discharge pressure generally cannot follow that same trajectory. Compare an installed map and system curve at equal useful flow and equal pressure duty; a generic throttling-power table does not establish actual savings.\n\n')
R('ch14','speed_sweep_claim','how compressor power varies with speed at fixed discharge pressure, illustrating the cubic power law','a fixed-pressure-ratio mass-flow sweep and contrasts it with a cubic affinity-law reference; these are different operating trajectories')
R('ch14','cubic_dominates','while with performance curves and speed variation, the cubic law dominates.', 'The cubic relation applies only to corresponding similar points with head changing as speed squared; it cannot be inferred from this fixed-pressure-ratio sweep.')
R('ch15','efficiency_definition',r'\eta_p = \frac{H_p}{H_{\text{actual}}} = \frac{H_p}{H_{\text{Euler}} \times \text{slip factor} - \text{losses}}',r'\eta_p = \frac{H_p}{h_{02}-h_{01}}', 'Efficiency denominator is actual total-enthalpy rise, not useful Euler head minus losses.')
R('ch15','head_zero','Head drops to zero or near zero','Head and efficiency can fall sharply, but sonic choking does not require zero head')
R('ch15','sound_approx',r'$$c_{\text{sonic}} = \sqrt{\frac{\gamma Z R T}{MW}}$$',r'$$c^2=\left(\frac{\partial P}{\partial\rho}\right)_s,\qquad c\simeq\sqrt{\frac{\gamma ZRT}{MW}}\quad\text{(constant-property approximation)}.$$')
R('ch15','referred_mach','These transformations ensure that the Mach number and flow coefficient are preserved, which are the dimensionless groups that determine the compressor\'s aerodynamic behavior.', 'These transformations preserve a reduced-speed approximation and the flow coefficient. Exact Mach similarity additionally requires the actual speed of sound (including changing heat-capacity ratio and real-gas derivatives); Reynolds number, volume ratio and gas-property similarity must also be assessed.')
S('ch15','simplified_corrections',r'For small deviations from reference conditions, the correction can be expressed.*?(?=## 15\.5)',r'''For corresponding points at the same flow coefficient and similar Mach/Reynolds conditions on the same machine,

$$\frac{Q_2}{Q_1}=\frac{N_2}{N_1},\qquad\frac{H_2}{H_1}\simeq\left(\frac{N_2}{N_1}\right)^2,\qquad\frac{W_2}{W_1}=\frac{\rho_2}{\rho_1}\frac{Q_2}{Q_1}\frac{H_2}{H_1}\frac{\eta_{p,1}}{\eta_{p,2}}.$$

At fixed speed, head in J/kg is primarily set by tip speed and aerodynamic loading; lowering gas molecular weight does not automatically increase delivered head. The head required for a specified pressure ratio generally increases for a lighter gas at the same temperature. Use the referred map to solve the operating point, then check pressure ratio, speed, surge and power together.

''')
R('ch15','recycle_margin',r'Q_{\text{recycle}} = Q_{\text{surge}}(N_{\text{max}}) - Q_{\text{process,min}}',r'Q_{\text{recycle,min}} = \max\!\left[0,(1+\mathrm{SM}/100)Q_{\text{surge}}(N_{\text{max}})-Q_{\text{process,min}}\right]', 'Recycle requirement omitted surge margin and nonnegative bound.')
R('ch15','valve_heat','Gas recycled through the anti-surge valve heats up due to compression and valve friction.', 'Compression adds enthalpy to the circulating gas. An adiabatic recycle valve conserves enthalpy between its inlet and outlet; it does not add shaft work, and its temperature can decrease through the Joule–Thomson effect. Repeated compression without sufficient heat rejection raises the loop temperature.')
R('ch15','head_temperature','Reduces compressor head (higher suction temperature)','Increases the head required for a fixed pressure ratio and changes the map operating point')
R('ch15','cold_indefinite','Indefinite — thermally stable','Sustained operation only within cooler, driver and control limits')
S('ch15','composition_table',r'\| MW decrease \|.*?\| \$T\$ increase \|.*?\|\n', '| MW decrease | Usually increases required J/kg for a specified pressure ratio; recalculate the map point |\n| $\gamma$ change | Changes temperature rise, sonic speed and efficiency conversion |\n| $Z$ change | Changes density and real-gas compression path |\n| $T$ increase | Increases inlet volume at fixed mass flow and typically increases required head |\n')
S('ch15','map_shift',r'The shift in the performance map can be visualized as:.*?(?=### 15\.8\.3)', 'Plot the corrected operating point at a declared actual or referred coordinate basis. Composition changes alter reduced speed, density and required pressure-ratio head; the entire actual head-flow map does not universally shift up/right for lighter gas.\n\n')
R('ch15','parallel_trip','Surge risk if one machine trips (remaining machines see increased flow, but discharge pressure drops, potentially pushing them toward surge)','Transient risk if one machine trips: header inventory, check-valve closure and controls determine the response. Increased forward flow with lower required head can move surviving machines toward high-flow choke; surge cannot be inferred from that condition alone')
R('ch15','api_current','API 617 (8th Edition)','API 617 (9th Edition, 2022)')
S('ch15','api_acceptance',r'API 617 specifies the following tolerances:.*?\*Table 15\.4:.*?\*','Performance acceptance must use the purchase specification, applicable API617 edition, specified ASME PTC10/ISO5389 test method, guarantee point and measurement uncertainty. Do not interpret a generic head/efficiency/power percentage table as an API acceptance clause. Record the contract tolerances and compare corrected test results on the same reference basis.', 'Removed unsupported normative acceptance tolerances.')
R('ch15','system_head',r'H_{\text{compressor}}(Q) = H_{\text{system}}(Q) = \frac{P_{\text{discharge}} - P_{\text{suction}}}{\rho \cdot g} + f(Q^2)',r'H_{\mathrm{compressor}}(Q)=H_{\mathrm{required}}(P_s,P_d,T_s,\mathbf{z},Q)', 'Removed liquid head-in-metres formula from gas polytropic head in J/kg.')
R('ch15','liquid_slug','can handle liquid slugs without damage (oil-flooded designs)','may tolerate a specified liquid fraction in qualified oil-flooded designs; slug size, liquid composition and thermal limits require vendor approval')
R('ch15','recip_required','Reciprocating is required.', 'Evaluate reciprocating and purpose-designed high-pressure centrifugal machines; pressure alone does not mandate one type.')
R('ch15','api_bib','8th ed. American Petroleum Institute.','9th ed. American Petroleum Institute.')
R('ch16','area_resistance','For thin-walled tubes, the simplified form based on the outside area is:', 'Multiplying by the outside area gives the following equivalent cylindrical-wall expression (no thin-wall approximation is required):')
R('ch16','ntu_limit','For a parallel flow exchanger:',r'For $C_r=1$, the counterflow limit is $\varepsilon=\mathrm{NTU}/(1+\mathrm{NTU})$. For $C_r\to0$, it is $1-e^{-\mathrm{NTU}}$. These relations assume constant heat-capacity rates; for mixture phase change use enthalpy segments and check internal temperature approaches.'+'\n\nFor a parallel flow exchanger:')
R('ch16','ltmd_P','where $R$ is the heat capacity ratio and $P$ is the thermal effectiveness.', 'Here $R=C_c/C_h$ and $P$ is the cold-side temperature-rise fraction, not necessarily the exchanger effectiveness based on $C_{min}$. Use the analytic limit or a numerically stable evaluation near $R=1$.')
R('ch16','temperature_cross','When a temperature cross exists, the LMTD correction factor drops rapidly, and a single TEMA E shell is insufficient. The solution is to use multiple shells in series or a TEMA F shell with a longitudinal baffle.', 'A temperature cross alone does not prove that a single shell is infeasible. Evaluate the appropriate effectiveness or F-factor relation for the actual pass arrangement and both terminal approaches. Add shells, change configuration or revise targets when the calculated thermal feasibility or chosen F-factor criterion fails.')
R('ch16','gas_power',r'W_{\text{stage}} = \frac{n}{n-1} \cdot \dot{m} R T_{\text{inlet}}',r'W_{\text{stage}} = \frac{1}{\eta_p}\frac{n}{n-1}\dot{m}\frac{RT_{\text{inlet}}}{M}', 'Ideal-gas compressor power omitted molar-mass and efficiency factors; M kg/mol and R J/mol/K.')
S('ch16','fake_cricondentherm',r'Gas export requires meeting a dewpoint specification \(typically.*?meets this specification\.', 'Gas export specifications define water and hydrocarbon dew points at a stated pressure or over a stated pressure interval. Cricondentherm is the maximum saturation temperature on the mixture envelope, not a universal standard. Cooling followed by condensate removal changes gas composition and can improve hydrocarbon dew point; a cooler alone does not remove the condensed material or establish compliance. Check the final export composition against the contract pressure basis.')
R('ch16','heatercooler_direction','**Accept a lower outlet temperature** — adjust the process to work with what the heat exchanger can deliver','**Revise the achievable outlet target** — insufficient heating gives a colder outlet; insufficient cooling gives a warmer outlet. Accept a change only if downstream constraints remain satisfied')
R('ch16','gpa_bib','GPSA Engineering Data Book (2017). 14th Edition','GPSA Engineering Data Book (2016). 14th Edition')
R('ch16','pinch_area','The area between the composite curves represents the heat transfer driving force.', 'The vertical temperature separation at a common enthalpy coordinate represents the local temperature driving force; the graphical area between curves is not itself that temperature difference.')
R('ch17','gas_choke_factor',r'\sqrt{\frac{x_T F_k M}{3 T_1 Z}}',r'\sqrt{\frac{x_T F_k M}{T_1 Z}}', 'Choked gas capacity had an erroneous additional factor of three under the square root.')
R('ch17','liquid_units',r'where $Q$ is the volumetric flow rate, $F_p$ is the piping geometry factor, $\Delta P$ is the pressure drop, $\rho$ is the fluid density, and $\rho_w$ is the water density at reference conditions.', r'In this Cv form, $Q$ is US gal/min and $\Delta P$ is psi; density ratio is dimensionless. For $Q$ in m³/hr and $\Delta P$ in bar use Kv. $F_p$ is the piping geometry factor. Gas pressures must be absolute.')
R('ch17','subcritical_liquid','The relationship follows the general orifice equation:', 'For an incompressible liquid (or a small gas density change), a screening relation is:')
R('ch17','relief_pressure','- $P_1$ = relieving pressure (set pressure × 1.1 + atmospheric)', '- $P_1$ = absolute relieving pressure in kPa: set gauge pressure plus the permitted overpressure plus atmospheric pressure. The permitted percentage depends on the relief scenario and applicable code; do not universally assume10%.')
R('ch17','relief_mw','- $M$ = molecular weight','- $M$ = molecular weight in kg/kmol (numerically g/mol)')
S('ch17','liquid_relief_SI',r'For liquid service \(incompressible flow\):.*?(?=### 17\.7\.6)',r'''For single-phase, nonflashing liquid, the physical SI sizing basis is

$$A=\frac{\dot m}{K_dK_wK_cK_v\sqrt{2\rho(P_1-P_2)}}.$$

Here $A$ is m², $\dot m$ is kg/s, pressure is Pa and density is kg/m³. $K_v$ here denotes the viscosity correction, distinct from a control valve's metric flow coefficient. Apply the applicable code's certified coefficient, backpressure and viscosity corrections, and its exact liquid-sizing procedure. Flashing/two-phase relief requires a suitable two-phase method; the incompressible formula is not valid there.

''')
R('ch17','insulation_factor','- $F$ = environment factor (1.0 for bare vessel, 0.3 for fireproofed)', '- $F$ = environment factor; use1.0 for the bare-vessel teaching case. Any insulation credit requires qualified fire performance and the applicable code calculation; 0.3 is not a universal fireproofing factor.')
S('ch17','flare_fake_momentum',r'The flare header is sized using the API 521 momentum criterion:.*?(?=The flare tip diameter)',r'''Size the flare header by calculating relief-case flow, density, pressure loss and built-up backpressure at each device. The dynamic-pressure quantity $\rho v^2$ has units Pa and may be a project screening limit, but it is neither a universal API521 carbon-steel limit nor equivalent to a Mach limit. Check Mach number, noise, vibration, liquid handling and flare-tip vendor capacity separately.

''')
R('ch17','fail_relief','| Pressure relief valve | Fail open | Prevent overpressure |','| Pressure relief valve | Self-actuated opening at its set condition | Not an ordinary fail-open control-valve actuator |')
R('ch17','fail_level','| Level control (separator) | Fail open | Prevent liquid carryover |','| Level control (separator) | Determine from hazard analysis | Balance high-level carryover against gas blowby into lower-pressure equipment |')
R('ch17','mode_two','**Mode 2: Specified $C_v$ and valve opening** — $C_v$ and percentage opening are set; NeqSim calculates outlet pressure and flow:', '**Mode 2: Specified $C_v$ and valve opening at imposed feed flow** — enable outlet-pressure calculation explicitly. The model solves the pressure needed for that flow; it cannot independently determine both flow and outlet pressure without another boundary condition:')
R('ch17','network_formula',r'Q = K_v \cdot \theta \cdot \sqrt{\Delta P \cdot \rho}',r'Q\,[\mathrm{m^3/hr}]=K_v\theta\sqrt{\frac{\Delta P\,[\mathrm{bar}]}{\rho/\rho_{w,ref}}}', 'Network choke equation incorrectly multiplied density for volumetric flow.')
R('ch17','critical_outlet','the outlet conditions are determined by the sonic throat conditions rather than the specified downstream pressure.', 'capacity is controlled by the throat condition. The downstream bulk stream remains at its specified or solved downstream pressure, and its equilibrium temperature is calculated there; do not replace that bulk state with the throat state.')
R('ch17','pressure_inflow',r'P_{\text{reservoir}} = P_{\text{separator}} + \Delta P_{\text{tubing}}',r'P_{\text{reservoir}} = P_{\text{separator}} + \Delta P_{\text{inflow}} + \Delta P_{\text{tubing}}', 'Reservoir-to-separator pressure budget omitted formation inflow loss.')
R('ch17','gpa_bib','GPSA Engineering Data Book (2017). 14th Edition','GPSA Engineering Data Book (2016). 14th Edition')
R('ch18','powerfactor',r'P_{total} = \sum_{i=1}^{n} P_{motor,i} \times \frac{SF_i}{\eta_i \times PF_i}',r'P_{\mathrm{active}}=\sum_i\frac{P_{\mathrm{shaft},i}}{\eta_i},\qquad S_i=\frac{P_{\mathrm{active},i}}{PF_i}', 'Power factor affects apparent power, not active energy consumption. Aggregate complex power for the system kVA rating.')
R('ch18','pf_prose','where $SF$ is the service factor (typically 1.0–1.15), $\eta$ is motor efficiency, and $PF$ is the power factor.', 'Here active power is kW and apparent power is kVA. Sum active and reactive powers separately for an aggregate power factor; add coincident-load and growth allowances explicitly. Motor service factor is a rating allowance, not normal consumed power. Include VFD losses in the electrical efficiency.')
R('ch18','half_load_conservation','This means operating two turbines at 75% load is less fuel-efficient than operating one at 100% load and one on standby—a key consideration for the power management system.', 'Two equal turbines at75% supply1.5 times one rating, so one turbine at100% plus standby cannot meet the same demand. Compare dispatches at equal total delivered power: for a1.5-rating demand, compare75%/75% with100%/50%, including minimum load, reserve and the actual heat-rate curves.')
R('ch18','turbine_poly','where $n$ is the polytropic exponent.',r'This expression is for compression. For an ideal-gas expansion, $\eta_{p,t}=[(n-1)/n]/[(\gamma-1)/\gamma]$. Here $n$ is the corresponding polytropic exponent.')
R('ch18','single_shaft_speed','The gas generator speed decreases, reducing both air flow and pressure ratio.', 'For a grid-connected single-shaft generator, synchronous speed remains essentially fixed and inlet-guide-vane/firing controls change airflow and temperature. A variable-speed gas generator can reduce speed and pressure ratio.')
R('ch18','combined_cycle_recovery',r'\eta_{CC} = \eta_{GT} + \eta_{ST} \times (1 - \eta_{GT}) = \eta_{GT} + \eta_{bottoming} \times (1 - \eta_{GT})',r'\eta_{CC}=\eta_{GT}+\eta_{\mathrm{ST,net}}\eta_{\mathrm{recovery}}(1-\eta_{GT})', 'Bottoming conversion must include recoverable exhaust fraction and parasitics.')
R('ch18','cc_example_domain','For a gas turbine at 38% and a bottoming cycle at 33%, the combined cycle efficiency is:', 'For a gas turbine at38%, a steam-cycle net efficiency of33% and idealized recovery of all remaining fuel energy ($\eta_{recovery}=1$), the upper screening estimate is:')
R('ch18','steam_heat',r'\dot{Q}_{process} \leq \sum_{k} \dot{m}_k h_k',r'\dot{Q}_{process} \leq \sum_k\dot{m}_k(h_{\mathrm{steam},k}-h_{\mathrm{return},k})', 'Useful process steam heat requires return enthalpy, not arbitrary absolute enthalpy.')
R('ch18','motor_start','**Instant startup** — No warm-up or ramp-up time required','**Controlled startup** — Electrical and mechanical ramp limits, lubrication, seals and process sequencing still apply')
R('ch18','vfd_guarantee','The affinity laws ensure that power consumption decreases with the cube of speed, providing the lowest energy consumption at any partial-load condition.', 'The cube law applies to dynamically similar points with unchanged density and efficiency, where required head also falls with speed squared. At fixed discharge pressure, use the actual map/system intersection; a lower speed can be unable to meet the pressure duty.')
S('ch18','vfd_economic_claim',r'The energy savings from VFD operation are dramatic.*?efficiency\)\.', 'The table is a teaching comparison of assumed trajectories, not equal-duty vendor performance. For15MW design power its assumed34% versus100% cases differ by9.9MW; actual annual savings require equal pressure/flow service, operating hours, losses and an explicit energy-price basis.')
R('ch18','wobbe_guarantee','A constant Wobbe Index ensures constant heat input to the combustor for a given fuel valve position, regardless of fuel composition changes.', 'At comparable pressure, temperature and a suitable unchoked orifice approximation, equal Wobbe index indicates similar heat input. It does not guarantee identical combustion stability, emissions or interchangeability; hydrogen fraction, flame speed and the OEM modified-Wobbe convention can also matter.')
R('ch18','gaslift_doublecount',r'Q_{sales} = Q_{total} - Q_{fuel} - Q_{flare} - Q_{lift}',r'Q_{sales}=Q_{\mathrm{fresh\ reservoir}}-Q_{fuel}-Q_{flare}-Q_{\mathrm{net\ reinjection}}-\Delta Q_{\mathrm{inventory}}', 'Internal recycled gas lift is not a permanent sales loss at a whole-field boundary; avoid double counting returned lift gas.')
R('ch18','Nplusone_guarantee','ensures that any single turbine failure does not cause production loss.', 'provides installed replacement capacity after one failure. A cold standby cannot instantaneously replace a tripped running unit; uninterrupted production additionally requires sufficient online reserve, energy storage or a validated transient load-shedding/ride-through strategy.')
R('ch18','dc_losses','HVDC transmission** eliminates capacitive losses and allows power transfer over any distance.', 'HVDC transmission** removes steady AC charging-current demand, but conductor and converter losses remain; practical distance and power capability still depend on design and economics.')
S('ch18','pinch_balance',r'\$\$\nQ_\{H,min\} =.*?\$\$\n\n\$\$\nQ_\{C,min\} =.*?\$\$',r'''$$Q_{H,\min}=-\min(0,\min_j R_j),\qquad Q_{C,\min}=Q_{H,\min}+R_{\mathrm{bottom}}.$$

Here $R_j$ is the cumulative unadjusted heat cascade from the highest shifted-temperature interval to interval $j$, using hot-minus-cold interval duties. Shift hot temperatures down and cold temperatures up by $\Delta T_{min}/2$. The added top utility makes every cascade residual nonnegative; the bottom residual is minimum cooling.''', 'Pinch utility equations mixed total cold duty with only above-pinch hot duty.')
R('ch18','onepct_efficiency','Improving gas turbine efficiency by 1% can increase saleable gas by 0.3–0.5% of total production—a significant economic impact over field life.', 'At fixed shaft load, fuel consumption changes inversely with thermal efficiency. A1% relative efficiency improvement saves approximately0.99% of fuel consumption, not0.3–0.5% of total gas production. Multiply by the actual fuel share to calculate the sales effect.')

progress=BOOK/'verification/scientific_revision/foundations_review_progress.json'
d=json.loads(progress.read_text(encoding='utf-8'));d['prose_read_complete']=list(range(1,19));d['remaining_prose']=[]
d['last_review_phase']='All18 chapters fully read; substantive correction and physical-gate work remains active.'
progress.write_text(json.dumps(d,indent=2),encoding='utf-8')
