"""Close remaining scientific-review findings in model domains and design interpretation."""
from revise_foundations_science_phase3 import R,S
R('ch02','water_exercise_basis','The gas composition is: CH$_4$ 90%, C$_2$H$_6$ 5%, C$_3$H$_8$ 3%, CO$_2$ 2%. Which EOS is more appropriate for this calculation and why?', 'The dry-gas composition is CH$_4$ 90%, C$_2$H$_6$ 5%, C$_3$H$_8$ 3%, CO$_2$ 2%. Add excess liquid water before selecting the mixing rule, enable a multiphase check, and compare the equilibrium gas-phase water mole fractions. A dry composition without a water inventory cannot represent water saturation. Which EOS is more appropriate and what independent data would test the result?')
R('ch03','MW_measurement_constraint','2. **Adjust plus fraction molecular weight** (±10%) to match saturation pressure','2. **Constrain plus-fraction molecular weight and density** to the measured values and their uncertainties; only vary them within a justified measurement uncertainty, preserving the characterized total inventory')
R('ch03','BIP_scope','The most sensitive BIPs for production optimization are:', 'The following are illustrative starting ranges, not transferable parameter recommendations. A BIP depends on the EOS, mixing rule, heavy-end definition and fitted data; a positive BIP does not guarantee the same saturation-pressure trend for every mixture. Retain the fitted parameter provenance and validate independent states:')
S('ch03','correlation_error_table', r'\| Property \| Best Correlation \| Typical Error \| Applicable Range \|.*?(?=For production optimization)', '''| Quantity | Selection and verification basis |
|----------|----------------------------------|
| Bubble pressure and solution GOR | Compare Standing or Vasquez–Beggs against the same measured black-oil data using the stated field units |
| Oil formation volume factor | Use the saturation correlation in its domain; above bubble pressure, use a consistent oil-compressibility relation |
| Oil viscosity | Distinguish dead, saturated and undersaturated oil; check temperature and solution-gas dependence against measurements |
| Gas formation volume factor | Compute from the EOS Z factor and explicitly defined reservoir and standard states |

An error percentage belongs to a specified validation dataset and metric; the formula name alone does not establish a universal accuracy ranking.

''')
R('ch04','Horner_pressure_meaning','gives $P^*$, which approximates the average reservoir pressure for an infinite-acting reservoir.', 'gives the extrapolated $P^*$. Under the constant-rate, infinite-acting homogeneous model it estimates the undisturbed reference pressure; in a depleted bounded reservoir it is not automatically the current volume-average pressure. Boundary corrections and production history are required for that interpretation.')
R('ch05','multiple_root_stability','The lower-rate intersection is unstable — any perturbation that reduces the rate will cause further rate decline (liquid loading). The upper-rate intersection is stable. If the well is started at a rate below the unstable point, it will die.', 'For the reduced scalar dynamic model $d q/dt=K[P_{\\mathrm{IPR}}(q)-P_{\\mathrm{VFP}}(q)]$ with $K>0$, a root is locally stable only if $d(P_{\\mathrm{IPR}}-P_{\\mathrm{VFP}})/dq<0$. This often makes a low-rate root unstable and a higher-rate root stable, but the ordering alone is not a proof. Wellbore storage, multiphase transients and controllers can change the stability; startup must be assessed dynamically.')
R('ch07','API14E_units_local','where $C$ is a constant (typically 100–150 for continuous service) and $\\rho_{mix}$ is the mixture density at flowing conditions.', 'Here a field-unit coefficient such as $C=100$ uses density in lb/ft³ and produces velocity in ft/s; its SI-equivalent coefficient is about 122 when density is kg/m³ and velocity m/s. These coefficients are screening conventions, not a solids-erosion or corrosion model.')
R('ch07','tree_recovery_evidence','Industry data suggests that dry tree completions achieve recovery factors 3–8% higher than subsea completions for the same reservoir, primarily because:', 'Tree architecture can affect intervention access, backpressure and economically available wells. A universal 3–8% recovery uplift is unsupported; assess the same reservoir and development constraints before attributing a recovery difference to tree type. Potential mechanisms include:')
R('ch07','twin_screw_gas','handle virtually any GVF, including 100% liquid or 100% gas.', 'can cover a broad gas-volume-fraction range when designed for it. Sustained operation near 100% gas may require liquid recirculation for sealing and cooling; duration, temperature rise, differential pressure and sand loading must remain within the vendor envelope.')
R('ch07','casing_factor_provenance','Design factors per NORSOK D-010:', 'Illustrative screening design-factor inputs are listed below; they have not been traced to a NORSOK D-010 clause and must not be used as a compliance table. Actual casing assessment includes load combinations, temperature, corrosion allowance, connection capacity and the applicable standard edition:')
R('ch09','asphaltene_lower_boundary','The pressure range between $P_{AOP}$ and $P_{bubble}$ is the asphaltene instability zone. Production operations should avoid sustained operation in this zone, or chemical inhibitors must be deployed.', 'An upper onset can lie above bubble pressure, while a lower redissolution boundary may lie below it. Bubble pressure is not itself the lower precipitation boundary. Determine both onsets along the actual composition and temperature path, then assess deposition kinetics, transport, residence time and tested mitigation before choosing an operating envelope.')
S('ch09','erosion_uncalibrated_table', r'The geometry factor is the critical parameter.*?(?=### 9.9.3)', 'Geometry and material coefficients must come from a specified erosion model and tests with consistent velocity units, impact angle, sand size and particle properties. The former universal material-coefficient and geometry-factor tables lacked that basis and cannot support a wall-loss calculation. A geometry that reduces erosion in one flow regime can increase it in another.\n\n')
R('ch09','blind_tee_geometry','long-radius bends (R/D ≥ 5) instead of standard elbows (R/D = 1.5) reduce the geometry factor by 50%. Blind tees should be avoided in sand service; use swept tees or target plates instead','compare bends, swept tees, blind tees and replaceable target elements using a calibrated model or relevant testing. Blind tees can protect some impact locations through particle redirection or a retained sand cushion, but can concentrate wear elsewhere; no universal 50% reduction or blanket prohibition follows from geometry alone')
R('ch14','soft_not_permission','**SOFT** — the constraint can be temporarily exceeded but triggers a warning','**SOFT** — software treatment may allow a penalized violation; this does not authorize a physical or operational limit exceedance')
R('ch14','design_not_lifetime','**DESIGN** — the constraint represents the normal design operating range; operating beyond it reduces equipment life but is physically possible','**DESIGN** — a declared reference range; the metadata alone establishes neither permissible operation beyond it nor a quantified equipment-life penalty')
R('ch14','normalization_direction',r'$$u_i = \frac{x_{\text{current},i}}{x_{\text{design},i}}$$',r'''For a positive upper limit, $u=x/x_{\max}$; for a positive lower limit, a suitable normalized form is $u=x_{\min}/x$. Implementations can instead use signed distances or explicit margins, so inspect each constraint's direction and units. The ratio for an upper limit must not be applied blindly to a minimum-speed or minimum-surge-margin constraint.''')
R('ch16','seawater_permit','maximum discharge temperature rise (typically 7 °C above ambient)','discharge temperature, mixing-zone and intake/outfall limits are site-permit inputs; there is no universal 7 °C allowance')
S('ch16','material_temperature_claim',r'\| Material \| Application \| Maximum Temperature \|.*?\| GRP \(fiberglass\).*?\n', '''| Material family | Required service qualification |
|-----------------|--------------------------------|
| Titanium | Chloride service, galvanic pairing, crevices and the actual temperature/pressure envelope |
| Copper–nickel | Velocity, impingement, sulfide contamination and protective-film conditions |
| Super duplex | Pitting/crevice corrosion, chlorination, temperature, weld condition and stress; a 250 °C generic seawater rating is not valid |
| Fiber-reinforced polymer | Resin system, pressure, temperature, fire exposure and installation standard |

Select material using the actual seawater chemistry, temperature, chlorination and design code with qualified vendor data; thermal stability alone is not corrosion suitability.
''')
R('ch18','HVDC_boundary','HVDC is preferred for cable lengths exceeding 80–100 km.', 'Compare AC compensation, voltage, delivered load and losses with converter cost and reliability at the actual route length; 80–100 km is not a universal AC/HVDC boundary.')
