"""Final resource/emissions accounting and scientific scope corrections."""
from revise_foundations_science_phase3 import R,S
R('ch13','dissolved_physical','dissolved hydrocarbons cannot be removed by physical separation','dissolved hydrocarbons are not removed efficiently by gravity separation or conventional deoiling hydrocyclones; adsorption, stripping and suitable membranes are different physical separation mechanisms')
R('ch13','barite_chemistry','cannot be dissolved by conventional chemical treatments','is poorly soluble in conventional mineral-acid treatments; qualified chelant formulations can remove some deposits')
R('ch13','activity_basis','where the bracketed terms are the ion activities in solution and $K_{sp}$ is the temperature- and pressure-dependent solubility product.','where activities are dimensionless relative to the selected standard state and $K_{sp}$ uses that same convention. The displayed expression is for a1:1 mineral; general minerals require stoichiometric activity powers. Concentration products without activity coefficients are only a dilute approximation.')
R('ch13','Fakhru_title','Review of technologies for oil and grease removal from wastewaters.','Review of technologies for oil and gas produced water treatment.')
S('ch18','dated_aggregate',r'On the Norwegian Continental Shelf alone, upstream facilities consume roughly 7 TWh.*?direct CO\$_2\$ emissions\.', 'Use a dated energy/emissions inventory for aggregate sector statistics; a platform model instead needs its measured power, heat, fuel and flare balances.')
S('ch18','scope_lifecycle',r'For an electrified platform receiving power from shore, Scope 1 emissions drop to near zero.*?over 95%\.',r'''Shore power removes the displaced onsite generation emissions, while residual fuel use, flaring, venting and fugitive emissions remain Scope1. Purchased-power accounting adds Scope2 using the applicable dated location-based and market-based methods. Grid-average reporting factors and marginal generation factors for a consequential decision are different quantities. A lifecycle claim additionally includes equipment, fuel/electricity supply chains and the chosen boundary; it cannot be inferred from turbine thermal efficiency alone.''')
S('ch18','marginal_grid',r'When shore power is sourced from renewable generation.*?(?=### Norwegian NCS Electrification Examples)',r'''For a matched useful electrical load, compare onsite fuel use and emissions with delivered shore electricity, cable/converter losses, backup generation and the remaining process heat supply. Report the date, geographic scope and accounting method of the electricity emission factor. For a consequential project assessment, analyze marginal supply and system response separately from the grid-average reporting factor; a fixed country-level range is not automatically a marginal factor.

''')
R('ch18','ORC_payback','At Norwegian carbon prices, ORC payback periods of 3–7 years are typical for suitable waste heat sources.','Calculate project payback using recoverable temperature-dependent duty, condenser conditions, net parasitic power, installation cost, dated energy/carbon prices and operating hours. A thermally feasible ORC does not establish a generic3–7year payback.')
R('ch18','electrification_summary','**Platform electrification** from shore power (AC for short distances, HVDC for >80 km) eliminates 50–80% of direct CO$_2$ emissions','**Platform electrification** requires a project-specific AC/HVDC comparison of load, distance, reactive compensation, conversion losses and reliability; there is no universal80km technology boundary. It reduces the emissions of displaced onsite generation')
R('ch18','electrification_fuelgain','Gas previously burned as fuel is now available for export (3–7% production uplift)','Displaced fuel may become available for export if sales capacity and process heat provision permit; quantify the actual saved fuel rather than assuming a fixed percentage uplift')
