"""Correct treatment, metering, control and exchanger limits."""
from revise_foundations_science_phase3 import R,S,BOOK
R('ch09','inhibitor_subcooling','| Effective subcooling | Unlimited (dose-dependent) | Unlimited (dose-dependent) | 6–14°C | Unlimited |','| Effective subcooling | Limited by equilibrium, concentration and freeze/viscosity envelope | Limited by equilibrium, concentration and losses | Product/fluid/time-dependent test envelope | Product/fluid/slurry-transport test envelope |')
R('ch09','inhibitor_holdtime','| Hold time | Indefinite | Indefinite | 12–72 hours | Indefinite |','| Hold time | Requires retained inhibitor concentration | Requires retained inhibitor concentration | Qualified induction/hold-time tests | Qualified agglomeration, settling and restart tests |')
R('ch09','inhibitor_shutin','| Shut-in protection | Yes | Yes | Limited | Yes |','| Shut-in protection | Verify concentration along the cooling path | Verify concentration and phase losses | Verify qualified hold time | Verify settling and restart behavior |')
R('ch09','inhibitor_recovery','| Recovery/regeneration | MEG reclamation plant | Not recovered (lost) | Not recovered | Not recovered |','| Recovery/regeneration | MEG regeneration/reclamation | Recovery possible where economical | Usually once-through | Usually once-through |')
R('ch09','PPD_WAT','| Chemical inhibitors | PPDs (pour point depressants) | Reduce WAT by 5–15°C |','| Chemical inhibitors | PPDs modify crystal morphology/network formation | Can improve pour point and yield stress; do not assume a lower equilibrium WAT |')
R('ch09','KD_name','**Richardson (1950) model**','**Krieger–Dougherty suspension relation**')
R('ch09','KD_scope','where $\phi_{max}$ is the maximum packing fraction (typically 0.74 for uniform spheres, 0.85–0.95 for polydisperse emulsions).','where $\phi_{max}$ is a fitted maximum packing fraction. The exponent uses the rigid-sphere intrinsic viscosity2.5; liquid droplets can deform and exchange interfacial stress, so this is an empirical emulsion approximation rather than a universal droplet law. Inversion also depends on wetting, shear history and phase viscosity.')
S('ch09','SI_erosion_units',r'where \$v_e\$ is the erosional velocity \(m/s\).*?60–80% of \$v_e\$\.',r'For the conventional field-unit coefficient $C$, this displayed equation gives ft/s when density is lb/ft³. In SI use $v_e=1.2193C/\sqrt{\rho_m}$ in m/s with density in kg/m³. The C-factor and any operating fraction are service assumptions; this screen does not establish sand erosion, corrosion or vibration acceptance.')
S('ch09','FIV_AIV',r'\*\*Flow-induced vibration \(FIV\)\*\* constraints.*?small-bore piping causes acoustic-induced vibration\.', '**Flow-induced vibration (FIV)** includes low-frequency structural response to turbulent or multiphase excitation. **Acoustic-induced vibration (AIV)** is a distinct high-frequency shell response often associated with high-energy gas pressure reduction. Velocity alone does not distinguish or accept either mechanism.')
R('ch09','corrosion_exercise','identify the temperature at which maximum corrosion occurs for each CO$_2$ level','show that this uncorrected relation increases monotonically with temperature at fixed CO$_2$ pressure. Explain why protective-film, pH and transport effects are needed to predict a nonmonotonic field trend')
S('ch11','reboiler_energy',r'\*\*Reboiler duty\*\*:.*?(?=### 11\.4\.6)',r'''**Reboiler duty** determines vapor traffic, but bottoms flow is not itself a vaporization rate. For the complete steady column, define positive $Q_R$ into the reboiler and positive $Q_C$ removed in the condenser:

$$Q_R-Q_C=\dot H_D+\dot H_B-\dot H_F.$$

All enthalpy flows are in W on one reference basis. An unrefluxed column has $Q_C=0$; any feed heater is outside this boundary. For the reboiler alone, use its incoming liquid, outgoing vapor and bottoms enthalpies. The checked examples specify heat input directly and verify the individual-stage and complete-column balance.

''')
R('ch11','D341_blending','for more accurate results, the Walther equation or ASTM D341 chart method should be used.','ASTM D341/Walther fits viscosity versus temperature for a given petroleum liquid, not arbitrary blend viscosity. Use measured blend data or a validated blending correlation at the same temperature; logarithmic mixing is only a screening estimate.')
R('ch11','Coriolis_proving','Direct mass measurement, no prover needed','Direct mass measurement; calibration/proving requirements still apply')
R('ch11','K_meter_factor','meter factor (K-factor) of a flow meter','meter calibration. A K-factor is pulses per unit volume; a meter factor is a dimensionless correction to indicated quantity')
S('ch11','meter_equation',r'The meter factor is calculated as:.*?(?=### 11\.10\.4)',r'''With both volumes corrected to one common basis, distinguish

$$K=\frac{N_{pulses}}{V_{reference}},\qquad MF=\frac{V_{reference}}{V_{indicated}}.$$

The first has units pulses/m³ and the second is dimensionless. A prover calculation includes calibrated base volume, steel temperature/pressure corrections and fluid temperature/pressure corrections as applicable; multiplying only the base volume by fluid CTL/CPL is not a complete proving procedure.

''')
R('ch11','exercise_heavy','A heavy oil field produces 28° API crude','A field produces 28° API crude')
R('ch11','exercise_pour','Calculate the blend viscosity and pour point if this crude is diluted with 30 vol% condensate','Estimate blend viscosity with an explicitly assumed mixing rule and identify the additional wax/blend test needed for pour point when the crude is diluted with30vol%condensate')
R('ch15','backward_impeller_coeff',r'a_0 = 0.5, \quad a_1 = 0.8, \quad a_2 = -0.3, \quad a_3 = 0.0',r'a_0=1.2,\quad a_1=0,\quad a_2=-0.2,\quad a_3=0')
R('ch15','backward_impeller_basis','A typical set for a backward-curved impeller:','An illustrative normalized curve with negative slope at the design point is:')
R('ch15','recycle_hot_time','Overheating if sustained > 5–10 minutes','Overheating time depends on gas inventory, power and heat rejection; calculate the transient')
R('ch16','TEMA_pressure_limit','| TEMA Class | Service | Design Pressure |\n|-----------|---------|----------------|\n| R | Petroleum and heavy-duty | Up to 200 bar |\n| C | General commercial | Moderate |\n| B | Chemical service | Standard |','| TEMA Class | Service emphasis | Pressure basis |\n|-----------|------------------|----------------|\n| R | Petroleum and heavy-duty | Actual design pressure and vessel code |\n| C | General commercial | Actual design pressure and vessel code |\n| B | Chemical service | Actual design pressure and vessel code |')
R('ch16','PCHE_coldbox','PCHEs are widely used in LNG plants for cryogenic service (cold boxes) and increasingly in CO₂ transport and compression applications.','PCHEs serve selected compact high-pressure duties, including CO₂ applications. A diffusion-bonded PCHE is distinct from a brazed-aluminum plate-fin exchanger commonly used in cryogenic cold boxes; do not transfer their pressure, fouling or material limits between technologies.')
R('ch17','installed_gain',r'\frac{N}{[1 + (1-N) \cdot (C_v/C_{v,\max})^2]^{3/2}}',r'\frac{N}{[N+(1-N)(C_v/C_{v,\max})^2]^{3/2}}')
R('ch17','installed_gain_basis',r'where $G_{\text{inherent}}$ is the inherent valve gain and $N$ is the valve authority.',r'For a fixed available pressure difference, noncavitating incompressible flow and quadratic nonvalve system resistance, let $c=C_v/C_{v,max}$. Then $Q/Q_{max}=c/[N+(1-N)c^2]^{1/2}$; differentiation gives the displayed gain. Here $N$ is authority at full opening and $G_{inherent}=dc/dl$. Other pump/system curves require their own derivation.')
R('ch17','mode2_calc','valve.setPercentValveOpening(75.0)\n```','valve.setPercentValveOpening(75.0)\nvalve.setIsCalcOutPressure(True)\n```')
S('ch17','radiation_table',r'\| Location \| Maximum Radiation \(kW/m²\) \|.*?(?=The radiation from an elevated flare)', 'Select radiation criteria from the applicable standard edition and project philosophy for the actual exposure duration, personnel access/PPE, escape, equipment temperature and materials. A heat-flux number alone is not a safe exposure-time limit; the previous table incorrectly associated6.31kW/m² with equipment over8hours.\n\n')
