"""Record the canonical routing fix and a read-only scan of this book's profiles."""
from pathlib import Path
import datetime
import hashlib
import json
import sys

BOOK = Path(__file__).resolve().parents[1]
PAPERLAB = BOOK.parents[1]
sys.path.insert(0, str(BOOK / '.build/python_packages'))
sys.path.insert(0, str(PAPERLAB / 'tools'))
import book_improvement_tools as improvement

chapters = improvement._collect_chapter_records(BOOK)
profiles = [improvement._chapter_skill_profile(chapter) for chapter in chapters]
assert len(profiles) == 35 and all(profile['skills'] for profile in profiles)
by_number = {profile['chapter_number']: profile for profile in profiles}
assert 'neqsim-production-optimization' in by_number[21]['skills']
assert 'numerical-methods' in by_number[31]['matched_topics']
assert 'neqsim-distillation-design' in by_number[33]['skills']
assert all(by_number[number]['routing_basis'] == 'title' for number in range(31, 36))
changed_files = [
    PAPERLAB / 'tools/book_improvement_tools.py',
    PAPERLAB / 'tests/test_book_skill_routing.py',
    PAPERLAB / 'skills/book_creation/SKILL.md',
    PAPERLAB / 'agents/book_author.paperlab.md',
]
report = {
    'status': 'passed',
    'reviewed_at_utc': datetime.datetime.now(datetime.timezone.utc).isoformat(),
    'python': sys.executable,
    'scope': 'Canonical advisory chapter skill routing, associated knowledge-graph skill edges, precise discussion-marker warning wording, and author/skill handoff guidance. No manuscript or calculation changes.',
    'changes': [
        'Replaced fixed chapter-number intervals with title-first topic matching, headings/content fallback, and nonempty general review skills.',
        'Exposed routing_basis and matched_topics for reviewer inspection; reordered chapters cannot change subject selection.',
        'Knowledge-graph skill edges use the same selector as the skill-stack chapter profiles.',
        'Changed plan and evidence warning messages to report absent explicit discussion markers rather than absent scientific prose.',
        'Added bidirectional book-author/book-creation/tool handoff guidance; suggestions remain advisory and require subject review.',
    ],
    'preserved': ['DISCUSSION_RE', 'figure normalizer', 'all book manuscript and notebook sources', 'numerical results and acceptance checks'],
    'tests': {
        'command': [sys.executable, str(PAPERLAB / 'tests/test_book_skill_routing.py'), '-v'],
        'dependency_directory': str(BOOK / '.build/python_packages'),
        'exit_code': 0,
        'observed_duration_seconds': 0.107,
        'passed': 3,
        'failed': 0,
        'cases': [
            {'name': 'test_reordered_manifest_keeps_skills_and_graph_edges', 'status': 'passed',
             'proof': 'Built the same three chapters in reversed manifest order; skill sets, actions and topics were identical by title; knowledge-graph edges exactly matched each profile.'},
            {'name': 'test_solver_onshore_and_unclassified_chapters_have_meaningful_profiles', 'status': 'passed',
             'proof': 'Solver/onshore specialist profiles were checked at chapter numbers2,21,31,33,35,90; heading/body fallback and an unknown-subject general review profile were also checked.'},
            {'name': 'test_missing_marker_warning_does_not_claim_missing_scientific_prose', 'status': 'passed',
             'proof': 'Plain scientific explanation without a special marker still triggers the unchanged heuristic, while both emitted warnings accurately describe missing markers.'},
        ],
    },
    'actual_book_scan': {
        'mode': 'read-only _collect_chapter_records and _chapter_skill_profile; no generated book plans overwritten',
        'chapters': len(profiles),
        'empty_profiles': 0,
        'profiles': profiles,
    },
    'files': [{'path': str(path), 'sha256': hashlib.sha256(path.read_bytes()).hexdigest()} for path in changed_files],
    'limitations': ['English keyword routing is advisory skill discovery, not semantic completeness or proof that any scientific review has been performed. Existing saved skill plans must be regenerated by the release owner.'],
}
destination = BOOK / 'verification/scientific_revision/skill_plan_routing_review.json'
destination.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding='utf-8')
print(json.dumps({'status': report['status'], 'chapters': len(profiles), 'empty_profiles': 0,
                  'selected': [{key: by_number[number][key] for key in ('chapter_number', 'title', 'routing_basis', 'matched_topics')}
                               for number in (21, 31, 32, 33, 34, 35)]}, indent=2))
