// Book styling — auto-generated by book_render_pdf.py
#set document(
  title: "Production Optimization of Oil and Gas Fields Using NeqSim",
  author: "Even Solbraa",
)

// Pandoc compatibility
#let horizontalrule = line(length: 100%, stroke: 0.5pt + luma(180))

// ── Page geometry ──
// Trim size and margins come from the publisher profile.
// Two-sided books use "inside"/"outside" so the binding margin alternates.
#set page(
  width: 170mm, height: 244mm,
  margin: (top: 19mm, bottom: 19mm, inside: 21mm, outside: 17mm),
  binding: left,
  numbering: "1",
  number-align: center,
  header: context {
    let pn = counter(page).get().first()
    if pn <= 1 { return [] }
    let openings = query(heading.where(level: 1)).filter(h => h.location().page() == pn)
    if openings.len() > 0 { return [] }
    let chapters = query(heading.where(level: 1).before(here()))
    if chapters.len() == 0 { return [] }
    let ends = query(<book-section-end>).filter(e => e.location().page() < pn)
    if ends.len() > 0 and ends.last().location().page() >= chapters.last().location().page() { return [] }
    let title = chapters.last().body
    set text(size: 8.5pt, fill: luma(110), tracking: 0.5pt)
    if calc.even(pn) {
      align(left)[#smallcaps[#title]]
    } else {
      align(right)[#smallcaps[#title]]
    }
  },
)

// ── Text & language ──
#set text(
  font: "Libertinus Serif",
  size: 10pt,
  lang: "en",
  hyphenate: true,
  number-type: "lining",
  ligatures: true,
)

// ── Paragraph typography ──
// Justified, controlled leading, first-line indent except after headings.
#set par(
  justify: true,
  leading: 0.72em,
  first-line-indent: (amount: 1.2em, all: false),
  spacing: 0.65em,
)

// ── Heading numbering ──
#set heading(numbering: "1.1")

// Reset equation counter at every chapter (level-1 heading)
#show heading.where(level: 1): it => {
  if it.numbering == none {
    return {
      pagebreak(weak: true)
      block(text(weight: "bold", size: 22pt, fill: rgb("#0d3b66"))[#it.body])
      v(1em)
    }
  }
  counter(math.equation).update(0)
  counter(figure.where(kind: image)).update(0)
  counter(figure.where(kind: table)).update(0)
  pagebreak(weak: true, to: "odd")
  v(1.5em)
  block[
    #text(size: 9pt, tracking: 2pt, fill: luma(120), weight: "regular")[
      #smallcaps[Chapter #counter(heading).display("1")]
    ]
    #v(0.4em)
    #line(length: 35%, stroke: 1pt + rgb("#0d3b66"))
    #v(0.6em)
    #text(weight: "bold", size: 22pt, hyphenate: false, fill: rgb("#0d3b66"))[#it.body]
  ]
  v(2em)
}

#show heading.where(level: 2): it => {
  v(1.4em)
  block(text(weight: "bold", size: 13pt, fill: rgb("#1a5276"))[#it])
  v(0.4em)
}

#show heading.where(level: 3): it => {
  v(1.0em)
  block(text(weight: "bold", size: 11.5pt)[#it])
  v(0.3em)
}

#show heading.where(level: 4): it => {
  v(0.7em)
  block(text(weight: "semibold", style: "italic", size: 11pt)[#it])
  v(0.2em)
}

// ── Equation numbering ──
// Display as (chapter.eq) with the chapter number coming from the heading
// counter. The counter is reset by the level-1 #show rule above.
#set math.equation(numbering: n => {
  let chs = counter(heading).get()
  let ch = if chs.len() > 0 { chs.first() } else { 0 }
  "(" + str(ch) + "." + str(n) + ")"
}, supplement: [Eq.])

// ── Tables: booktabs style (top / mid / bottom horizontal rules only) ──
// Stroke is applied via show rule on the first/last row hlines from pandoc.
#set table(
  stroke: none,
  inset: (x: 8pt, y: 5pt),
)

// Booktabs-style horizontal rules: thicker at top and bottom, thin under
// the header row. Pandoc emits standard #table; we recolor the outer rules.
#show table: it => {
  set text(size: 8.2pt)
  block(breakable: true, stroke: (top: 1pt + black, bottom: 1pt + black), it)
}

// ── Figures ──
#set figure(numbering: n => {
  let ch = counter(heading).get().first()
  str(ch) + "." + str(n)
})
#show figure: it => {
  block(breakable: it.kind == table, {
  v(0.5em)
  align(center)[#it.body]
  v(0.3em)
  align(center)[
    #set text(size: 9pt, style: "italic", fill: luma(80))
    #it.caption
  ]
  v(0.8em)
  })
}

// ── Code blocks ──
#show raw.where(block: true): it => {
  set text(size: 7.2pt, font: "DejaVu Sans Mono")
  // Add discretionary, zero-width wrapping opportunities to highlighted lines.
  // This is layout only: raw.text and the manuscript source remain verbatim.
  // Punctuation handles member chains/calls; bounded runs handle long literals.
  show raw.line: line => {
    show regex("[.,;()\\\\[\\\\]{}_/]"): item => item + sym.zws
    show regex("[^\\\\s]{24}"): item => item + sym.zws
    line.body
  }
  block(
    width: 100%,
    inset: 9pt,
    fill: luma(247),
    radius: 3pt,
    stroke: (left: 2.5pt + rgb("#1a5276")),
    breakable: true,
    it
  )
}

#show raw.where(block: false): it => {
  box(
    fill: luma(244),
    inset: (x: 3pt, y: 1pt),
    outset: (y: 1pt),
    radius: 2pt,
    text(size: 0.92em, font: "DejaVu Sans Mono")[#it]
  )
}

// ── Block quotes ──
#show quote.where(block: true): it => {
  block(
    inset: (left: 12pt, y: 6pt),
    stroke: (left: 2pt + rgb("#1a5276").lighten(20%)),
    text(style: "italic", fill: luma(70))[#it.body]
  )
}

#show figure.where(kind: table): set block(breakable: true)
#set heading(numbering: none)
= Before Glossary
A preceding section with substantive text.
#pagebreak()
== Glossary
<glossary>
#figure(
  align(center)[#table(
    columns: 2,
    align: (auto,auto,),
    table.header([Term], [Definition],),
    table.hline(),
    [#strong[AGA]], [American Gas Association --- standards for gas measurement and quality],
    [#strong[Agentic AI]], [AI systems that autonomously plan, execute, and adapt multi-step workflows using external tools and structured protocols],
    [#strong[Anti-surge control]], [Control that maintains margin from compressor surge, commonly by recycling gas; its effectiveness depends on the map, sensors, valve dynamics and implemented logic.],
    [#strong[API gravity]], [Petroleum-liquid density scale: 141.5/SG(60/60 °F) − 131.5. The reference temperatures are part of the definition.],
    [#strong[Artificial lift]], [Methods to increase flow from wells, including gas lift, ESP, and rod pumps],
    [#strong[Automatic differentiation (AD)]], [Chain-rule differentiation of implemented elementary operations, accurate to floating-point arithmetic for the differentiable executed path; branches and numerical solvers need appropriate derivative treatment.],
    [#strong[Back-pressure]], [The pressure at the outlet of a production system or equipment item],
    [#strong[BHP]], [Bottomhole pressure at a stated well datum; flowing BHP differs from average reservoir pressure and from shut-in pressure.],
    [#strong[BOE]], [Barrel of oil equivalent; an energy-equivalent reporting quantity whose conversion factor and heating-value basis must be stated.],
    [#strong[Bottleneck]], [The equipment or process constraint that limits total system throughput],
    [#strong[Bubble point]], [For a specified mixture and temperature, the pressure at which an infinitesimal vapor phase first coexists with the liquid; a bubble-point temperature can instead be defined at fixed pressure.],
    [#strong[Capacity check]], [Comparison of operating demands with explicitly configured equipment limits, subject to the rating basis, model applicability and completeness of the checked constraints.],
    [#strong[CCR]], [Cricondenbar: maximum pressure of vapor--liquid coexistence for a specified mixture; not necessarily the mixture critical pressure.],
    [#strong[CCT]], [Cricondentherm: maximum temperature of vapor--liquid coexistence for a specified mixture; not a standard or necessarily the critical temperature.],
    [#strong[Choke]], [A valve that restricts flow, typically at the wellhead or manifold, to control production rate],
    [#strong[Compressor curve]], [Performance map showing the relationship between flow, head, power, and efficiency for a compressor],
    [#strong[Compressor surge]], [Low-flow system instability involving pressure and flow oscillations, potentially including flow reversal; the boundary depends on the compressor and connected system.],
    [#strong[Conformal prediction]], [Prediction-set calibration with finite-sample marginal coverage under the method's assumptions, commonly exchangeability; it does not guarantee conditional coverage or remain valid under arbitrary distribution shift.],
    [#strong[CPA]], [Cubic Plus Association equation of state],
    [#strong[Cv value]], [Valve flow coefficient based on US gallons per minute of water at about 60 °F producing a 1 psi pressure drop. Gas, cavitation and choked-flow calculations require the appropriate sizing relations.],
    [#strong[DeepONet]], [Deep Operator Network: a learned mapping between function spaces, used as a surrogate for solution operators within a demonstrated training and validation domain.],
    [#strong[Dew point]], [The temperature (at a given pressure) where the first liquid droplet forms from a gas],
    [#strong[Digital twin]], [A computational representation connected to observations of a physical asset, with defined update, synchronization and validation procedures; connection alone does not establish accuracy.],
    [#strong[EOS]], [Equation of state --- thermodynamic model relating P, V, T, and composition],
    [#strong[ESP]], [Electrical submersible pump --- an artificial lift method],
    [#strong[Flash calculation]], [Equilibrium phase amounts and compositions at specified constraints, such as temperature/pressure or enthalpy/pressure; more than two phases may be present.],
    [#strong[Flow assurance]], [Engineering discipline managing flow-related risks (hydrate, wax, slugging, corrosion)],
    [#strong[FNO]], [Fourier Neural Operator --- operator learning architecture that works in Fourier space for efficient PDE surrogate models],
    [#strong[FPSO]], [Floating Production, Storage, and Offloading vessel],
    [#strong[GOR]], [Gas-oil ratio --- volume of gas produced per volume of oil at standard conditions],
    [#strong[Gymnasium]], [Python RL library (successor to OpenAI Gym) defining standard environment API: reset(), step(), observation/action/reward spaces],
    [#strong[HP separator]], [High-pressure separator --- the first-stage separator in a separation train],
    [#strong[HYSYS]], [Aspen HYSYS, an AspenTech process simulator. Honeywell UniSim Design is a separate product.],
    [#strong[IPR]], [Inflow Performance Relationship --- relates wellbore flowing pressure to production rate],
    [#strong[ISO 6976]], [International standard for calculating calorific value of natural gas],
    [#strong[JT cooling]], [Cooling during approximately isenthalpic throttling when the Joule--Thomson coefficient is positive. Throttling can instead heat a fluid when that coefficient is negative.],
    [#strong[K-factor]], [Here, the Souders--Brown separator capacity factor, with velocity units; distinguish it from the dimensionless phase-equilibrium ratio K\_i = y\_i/x\_i.],
    [#strong[LP separator]], [Low-pressure separator --- a later stage in a separation train],
    [#strong[LMTD]], [Log-mean temperature difference --- used in heat exchanger design],
    [#strong[MCP]], [Model Context Protocol --- standardized protocol enabling LLMs to discover and use external tools (e.g., simulation capabilities)],
    [#strong[MEG]], [Mono-ethylene glycol --- hydrate inhibitor],
    [#strong[Mixing rule]], [Method for combining pure-component EOS parameters to model mixtures],
    [#strong[MMSCFD]], [Million standard cubic feet per day --- gas flow rate unit],
    [#strong[Monte Carlo dropout]], [Approximate uncertainty estimation from repeated stochastic network evaluations with dropout; prediction spread needs calibration and is not automatically a reliable physical-error bound.],
    [#strong[Multiphase flow]], [Simultaneous transport of two or more phases, for example gas--liquid, oil--water or gas--oil--water.],
    [#strong[NeqSim]], [Non-equilibrium Simulator --- open-source Java library for thermodynamic and process simulation],
    [#strong[NGL]], [Natural gas liquids --- ethane, propane, butane, and heavier hydrocarbons],
    [#strong[NORSOK]], [Norwegian standards for petroleum industry activities],
    [#strong[NPV]], [Net present value: the sum of cash flows, including initial investment, discounted to a specified valuation date using a stated discount-rate convention.],
    [#strong[OPR]], [Outflow performance relationship: pressure required to transport a specified rate through tubing and downstream equipment for stated outlet and thermal conditions.],
    [#strong[Phase envelope]], [Diagram showing the boundary between single-phase and two-phase regions],
    [#strong[PI]], [Productivity index: production rate divided by pressure drawdown on a stated flow/pressure basis; the linear relation has an applicability range.],
    [#strong[Polytropic efficiency]], [For compression, the ratio of differential ideal pressure work to differential actual enthalpy rise along the compression path; real-gas evaluation requires thermodynamic properties and a defined method.],
    [#strong[PR EOS]], [Peng-Robinson equation of state],
    [#strong[ProcessSystem]], [NeqSim Java class representing a complete process flowsheet],
    [#strong[PVT]], [Pressure-Volume-Temperature --- laboratory measurements of fluid properties],
    [#strong[Riser]], [Vertical or near-vertical pipe connecting subsea infrastructure to a surface facility],
    [#strong[SRK EOS]], [Soave-Redlich-Kwong equation of state],
    [#strong[Separator]], [Vessel that separates a multiphase stream into gas, oil, and water phases],
    [#strong[Slug flow]], [Intermittent multiphase flow pattern with alternating gas and liquid slugs],
    [#strong[Surge line]], [The locus of minimum stable flow points on a compressor performance map],
    [#strong[TEG]], [Triethylene glycol --- used for gas dehydration],
    [#strong[TPflash]], [Temperature-pressure flash --- phase equilibrium calculation at given T and P],
    [#strong[Turndown]], [The ability of equipment to operate below design capacity],
    [#strong[UA]], [Overall heat transfer coefficient times area --- characterizes heat exchanger performance],
    [#strong[Utilization]], [Dimensionless operating demand divided by the relevant declared limit; separate limits may apply to power, actual volume, gas load, liquid retention or other quantities.],
    [#strong[VFP]], [Vertical Flow Performance --- well/tubing pressure-rate relationship tables],
    [#strong[VLE]], [Vapor-liquid equilibrium],
    [#strong[Wellhead]], [Surface equipment at the top of a well],
    [#strong[Affinity laws]], [Approximate centrifugal-machine similarity relations: flow scales with speed, head with speed squared and power with density times speed cubed, for fixed geometry and comparable operating conditions.],
    [#strong[Brayton cycle]], [Thermodynamic cycle underlying gas turbine operation --- compression, combustion, expansion],
    [#strong[CCGT]], [Combined cycle gas turbine --- gas turbine with heat recovery steam generator and steam turbine],
    [#strong[CapacityConstrainedEquipment]], [NeqSim interface enabling equipment to self-report capacity limits (HARD, SOFT, DESIGN types)],
    [#strong[CAPEX]], [Capital expenditure --- investment cost for equipment, facilities, or modifications],
    [#strong[Carbon intensity]], [Emissions divided by a declared production or energy measure, with system boundary, gas coverage and CO2-equivalent convention stated.],
    [#strong[Decline curve]], [Empirical production-rate trend, such as an Arps model; fitted coefficients and flow-regime applicability do not by themselves establish recoverable reserves.],
    [#strong[EUR]], [Estimated ultimate recovery --- total hydrocarbon volume expected from a well or field],
    [#strong[HRSG]], [Heat recovery steam generator --- extracts energy from gas turbine exhaust],
    [#strong[HVDC]], [High-voltage direct current --- used for long-distance power transmission to offshore platforms],
    [#strong[IRR]], [Discount rate at which project NPV is zero; cash-flow patterns can produce multiple IRRs or no economically useful root.],
    [#strong[KHI]], [Kinetic hydrate inhibitor --- polymer that slows hydrate nucleation and growth],
    [#strong[Latin Hypercube Sampling]], [Stratified sampling that covers each marginal probability interval once; it does not guarantee uniform coverage of all joint combinations.],
    [#strong[LoopedPipeNetwork]], [NeqSim class for solving interconnected well/pipeline network hydraulics],
    [#strong[MPC]], [Model predictive control --- advanced control strategy using a process model for future prediction],
    [#strong[Monte Carlo simulation]], [Computational method using random sampling to model uncertainty in outcomes],
    [#strong[MultiScenarioVFPGenerator]], [NeqSim class for generating VFP tables across parameter ranges (WC, GOR, pressure)],
    [#strong[OPEX]], [Operating expenditure --- recurring costs for running a facility],
    [#strong[OptimizationConfig]], [NeqSim builder class for configuring search algorithms, tolerances, and caching],
    [#strong[ONNX]], [Open Neural Network Exchange --- standardized format for exporting trained neural network models between frameworks (PyTorch, TensorFlow, Java)],
    [#strong[OptimizationResult]], [NeqSim class containing optimal rate, bottleneck, iteration history, and diagnostics],
    [#strong[ORC]], [Organic Rankine Cycle --- power generation from low-grade waste heat using organic working fluids],
    [#strong[P10/P50/P90]], [Quantile labels requiring an explicit convention. Under non-exceedance, P10 is the 10th percentile; petroleum resource exceedance notation commonly uses P10 for the high case and P90 for the low case.],
    [#strong[Pareto front]], [Set of solutions where no objective can be improved without worsening another],
    [#strong[PFS]], [Power from shore --- supplying offshore platforms with onshore electricity],
    [#strong[PINN]], [Physics-informed neural network: includes equation residuals or physical constraints in training. Soft penalty terms encourage, but do not guarantee, conservation or an accurate solution.],
    [#strong[PPO]], [Proximal Policy Optimization --- policy gradient RL algorithm using clipped surrogate objective for stable training],
    [#strong[ProcessAutomation]], [NeqSim API providing string-addressable variable access for process models],
    [#strong[ProcessModel]], [NeqSim class for composing multiple ProcessSystem objects into a multi-area plant model],
    [#strong[ProductionOptimizer]], [NeqSim class for automated production rate maximization subject to equipment constraints],
    [#strong[Rachford-Rice]], [Equation relating phase fraction to K-values and feed composition in flash calculations],
    [#strong[Recycle]], [NeqSim recycle-stream convergence equipment supporting direct substitution and optional acceleration; acceptance still requires residual and conservation checks.],
    [#strong[Reinforcement learning (RL)]], [Training an agent to make sequential decisions by interacting with an environment and maximizing cumulative reward],
    [#strong[Robust optimization]], [Optimization imposing feasibility or performance requirements over a specified uncertainty set; coverage is limited to that set and the chosen formulation.],
    [#strong[SAC]], [Soft Actor-Critic --- off-policy RL algorithm combining actor-critic with maximum entropy for exploration],
    [#strong[Scope 1/2 emissions]], [Scope 1 covers direct emissions from owned or controlled sources; Scope 2 covers indirect emissions from purchased electricity, steam, heat and cooling.],
    [#strong[Sim-to-real transfer]], [Deploying policies trained in simulation to real-world systems, addressing the gap between model and reality],
    [#strong[Stochastic optimization]], [Optimization using probability models for uncertain inputs, through sampling, probability-weighted scenarios or other stochastic formulations.],
    [#strong[Surrogate model]], [Simplified mathematical model (e.g., neural network) trained to approximate a complex simulator],
    [#strong[SurrogateEquipment]], [Proposed NeqSim class wrapping a trained neural network in the standard equipment interface for hybrid physics-AI simulation],
    [#strong[Tornado diagram]], [Ranked one-at-a-time sensitivity ranges for a declared input variation and baseline; the bars are not generally a variance decomposition or probability distribution.],
    [#strong[UQ]], [Uncertainty quantification: identifying, propagating and assessing uncertainties in inputs, observations, parameters and models with explicit assumptions and calibration evidence.],
    [#strong[VFD]], [Variable frequency drive --- controls motor speed for energy-efficient equipment operation],
    [#strong[Wobbe index]], [Calorific value divided by the square root of gas relative density to air, using consistent reference conditions and gross/net basis; this is an interchangeability indicator, not a complete burner-compatibility test.],
  )]
  , kind: table
  )
